################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../net/netfilter/core.c \
../net/netfilter/nf_conntrack_acct.c \
../net/netfilter/nf_conntrack_amanda.c \
../net/netfilter/nf_conntrack_core.c \
../net/netfilter/nf_conntrack_ecache.c \
../net/netfilter/nf_conntrack_expect.c \
../net/netfilter/nf_conntrack_extend.c \
../net/netfilter/nf_conntrack_ftp.c \
../net/netfilter/nf_conntrack_h323_asn1.c \
../net/netfilter/nf_conntrack_h323_main.c \
../net/netfilter/nf_conntrack_h323_types.c \
../net/netfilter/nf_conntrack_helper.c \
../net/netfilter/nf_conntrack_irc.c \
../net/netfilter/nf_conntrack_l3proto_generic.c \
../net/netfilter/nf_conntrack_netbios_ns.c \
../net/netfilter/nf_conntrack_netlink.c \
../net/netfilter/nf_conntrack_pptp.c \
../net/netfilter/nf_conntrack_proto.c \
../net/netfilter/nf_conntrack_proto_dccp.c \
../net/netfilter/nf_conntrack_proto_generic.c \
../net/netfilter/nf_conntrack_proto_gre.c \
../net/netfilter/nf_conntrack_proto_sctp.c \
../net/netfilter/nf_conntrack_proto_tcp.c \
../net/netfilter/nf_conntrack_proto_udp.c \
../net/netfilter/nf_conntrack_proto_udplite.c \
../net/netfilter/nf_conntrack_sane.c \
../net/netfilter/nf_conntrack_sip.c \
../net/netfilter/nf_conntrack_standalone.c \
../net/netfilter/nf_conntrack_tftp.c \
../net/netfilter/nf_log.c \
../net/netfilter/nf_queue.c \
../net/netfilter/nf_sockopt.c \
../net/netfilter/nf_tproxy_core.c \
../net/netfilter/nfnetlink.c \
../net/netfilter/nfnetlink_log.c \
../net/netfilter/nfnetlink_queue.c \
../net/netfilter/x_tables.c \
../net/netfilter/xt_CLASSIFY.c \
../net/netfilter/xt_CONNMARK.c \
../net/netfilter/xt_CONNSECMARK.c \
../net/netfilter/xt_CT.c \
../net/netfilter/xt_DSCP.c \
../net/netfilter/xt_HL.c \
../net/netfilter/xt_LED.c \
../net/netfilter/xt_MARK.c \
../net/netfilter/xt_NFLOG.c \
../net/netfilter/xt_NFQUEUE.c \
../net/netfilter/xt_NOTRACK.c \
../net/netfilter/xt_RATEEST.c \
../net/netfilter/xt_SECMARK.c \
../net/netfilter/xt_TCPMSS.c \
../net/netfilter/xt_TCPOPTSTRIP.c \
../net/netfilter/xt_TPROXY.c \
../net/netfilter/xt_TRACE.c \
../net/netfilter/xt_cluster.c \
../net/netfilter/xt_comment.c \
../net/netfilter/xt_connbytes.c \
../net/netfilter/xt_connlimit.c \
../net/netfilter/xt_connmark.c \
../net/netfilter/xt_conntrack.c \
../net/netfilter/xt_dccp.c \
../net/netfilter/xt_dscp.c \
../net/netfilter/xt_esp.c \
../net/netfilter/xt_hashlimit.c \
../net/netfilter/xt_helper.c \
../net/netfilter/xt_hl.c \
../net/netfilter/xt_iprange.c \
../net/netfilter/xt_length.c \
../net/netfilter/xt_limit.c \
../net/netfilter/xt_mac.c \
../net/netfilter/xt_mark.c \
../net/netfilter/xt_multiport.c \
../net/netfilter/xt_osf.c \
../net/netfilter/xt_owner.c \
../net/netfilter/xt_physdev.c \
../net/netfilter/xt_pkttype.c \
../net/netfilter/xt_policy.c \
../net/netfilter/xt_quota.c \
../net/netfilter/xt_rateest.c \
../net/netfilter/xt_realm.c \
../net/netfilter/xt_recent.c \
../net/netfilter/xt_sctp.c \
../net/netfilter/xt_socket.c \
../net/netfilter/xt_state.c \
../net/netfilter/xt_statistic.c \
../net/netfilter/xt_string.c \
../net/netfilter/xt_tcpmss.c \
../net/netfilter/xt_tcpudp.c \
../net/netfilter/xt_time.c \
../net/netfilter/xt_u32.c 

OBJS += \
./net/netfilter/core.o \
./net/netfilter/nf_conntrack_acct.o \
./net/netfilter/nf_conntrack_amanda.o \
./net/netfilter/nf_conntrack_core.o \
./net/netfilter/nf_conntrack_ecache.o \
./net/netfilter/nf_conntrack_expect.o \
./net/netfilter/nf_conntrack_extend.o \
./net/netfilter/nf_conntrack_ftp.o \
./net/netfilter/nf_conntrack_h323_asn1.o \
./net/netfilter/nf_conntrack_h323_main.o \
./net/netfilter/nf_conntrack_h323_types.o \
./net/netfilter/nf_conntrack_helper.o \
./net/netfilter/nf_conntrack_irc.o \
./net/netfilter/nf_conntrack_l3proto_generic.o \
./net/netfilter/nf_conntrack_netbios_ns.o \
./net/netfilter/nf_conntrack_netlink.o \
./net/netfilter/nf_conntrack_pptp.o \
./net/netfilter/nf_conntrack_proto.o \
./net/netfilter/nf_conntrack_proto_dccp.o \
./net/netfilter/nf_conntrack_proto_generic.o \
./net/netfilter/nf_conntrack_proto_gre.o \
./net/netfilter/nf_conntrack_proto_sctp.o \
./net/netfilter/nf_conntrack_proto_tcp.o \
./net/netfilter/nf_conntrack_proto_udp.o \
./net/netfilter/nf_conntrack_proto_udplite.o \
./net/netfilter/nf_conntrack_sane.o \
./net/netfilter/nf_conntrack_sip.o \
./net/netfilter/nf_conntrack_standalone.o \
./net/netfilter/nf_conntrack_tftp.o \
./net/netfilter/nf_log.o \
./net/netfilter/nf_queue.o \
./net/netfilter/nf_sockopt.o \
./net/netfilter/nf_tproxy_core.o \
./net/netfilter/nfnetlink.o \
./net/netfilter/nfnetlink_log.o \
./net/netfilter/nfnetlink_queue.o \
./net/netfilter/x_tables.o \
./net/netfilter/xt_CLASSIFY.o \
./net/netfilter/xt_CONNMARK.o \
./net/netfilter/xt_CONNSECMARK.o \
./net/netfilter/xt_CT.o \
./net/netfilter/xt_DSCP.o \
./net/netfilter/xt_HL.o \
./net/netfilter/xt_LED.o \
./net/netfilter/xt_MARK.o \
./net/netfilter/xt_NFLOG.o \
./net/netfilter/xt_NFQUEUE.o \
./net/netfilter/xt_NOTRACK.o \
./net/netfilter/xt_RATEEST.o \
./net/netfilter/xt_SECMARK.o \
./net/netfilter/xt_TCPMSS.o \
./net/netfilter/xt_TCPOPTSTRIP.o \
./net/netfilter/xt_TPROXY.o \
./net/netfilter/xt_TRACE.o \
./net/netfilter/xt_cluster.o \
./net/netfilter/xt_comment.o \
./net/netfilter/xt_connbytes.o \
./net/netfilter/xt_connlimit.o \
./net/netfilter/xt_connmark.o \
./net/netfilter/xt_conntrack.o \
./net/netfilter/xt_dccp.o \
./net/netfilter/xt_dscp.o \
./net/netfilter/xt_esp.o \
./net/netfilter/xt_hashlimit.o \
./net/netfilter/xt_helper.o \
./net/netfilter/xt_hl.o \
./net/netfilter/xt_iprange.o \
./net/netfilter/xt_length.o \
./net/netfilter/xt_limit.o \
./net/netfilter/xt_mac.o \
./net/netfilter/xt_mark.o \
./net/netfilter/xt_multiport.o \
./net/netfilter/xt_osf.o \
./net/netfilter/xt_owner.o \
./net/netfilter/xt_physdev.o \
./net/netfilter/xt_pkttype.o \
./net/netfilter/xt_policy.o \
./net/netfilter/xt_quota.o \
./net/netfilter/xt_rateest.o \
./net/netfilter/xt_realm.o \
./net/netfilter/xt_recent.o \
./net/netfilter/xt_sctp.o \
./net/netfilter/xt_socket.o \
./net/netfilter/xt_state.o \
./net/netfilter/xt_statistic.o \
./net/netfilter/xt_string.o \
./net/netfilter/xt_tcpmss.o \
./net/netfilter/xt_tcpudp.o \
./net/netfilter/xt_time.o \
./net/netfilter/xt_u32.o 

C_DEPS += \
./net/netfilter/core.d \
./net/netfilter/nf_conntrack_acct.d \
./net/netfilter/nf_conntrack_amanda.d \
./net/netfilter/nf_conntrack_core.d \
./net/netfilter/nf_conntrack_ecache.d \
./net/netfilter/nf_conntrack_expect.d \
./net/netfilter/nf_conntrack_extend.d \
./net/netfilter/nf_conntrack_ftp.d \
./net/netfilter/nf_conntrack_h323_asn1.d \
./net/netfilter/nf_conntrack_h323_main.d \
./net/netfilter/nf_conntrack_h323_types.d \
./net/netfilter/nf_conntrack_helper.d \
./net/netfilter/nf_conntrack_irc.d \
./net/netfilter/nf_conntrack_l3proto_generic.d \
./net/netfilter/nf_conntrack_netbios_ns.d \
./net/netfilter/nf_conntrack_netlink.d \
./net/netfilter/nf_conntrack_pptp.d \
./net/netfilter/nf_conntrack_proto.d \
./net/netfilter/nf_conntrack_proto_dccp.d \
./net/netfilter/nf_conntrack_proto_generic.d \
./net/netfilter/nf_conntrack_proto_gre.d \
./net/netfilter/nf_conntrack_proto_sctp.d \
./net/netfilter/nf_conntrack_proto_tcp.d \
./net/netfilter/nf_conntrack_proto_udp.d \
./net/netfilter/nf_conntrack_proto_udplite.d \
./net/netfilter/nf_conntrack_sane.d \
./net/netfilter/nf_conntrack_sip.d \
./net/netfilter/nf_conntrack_standalone.d \
./net/netfilter/nf_conntrack_tftp.d \
./net/netfilter/nf_log.d \
./net/netfilter/nf_queue.d \
./net/netfilter/nf_sockopt.d \
./net/netfilter/nf_tproxy_core.d \
./net/netfilter/nfnetlink.d \
./net/netfilter/nfnetlink_log.d \
./net/netfilter/nfnetlink_queue.d \
./net/netfilter/x_tables.d \
./net/netfilter/xt_CLASSIFY.d \
./net/netfilter/xt_CONNMARK.d \
./net/netfilter/xt_CONNSECMARK.d \
./net/netfilter/xt_CT.d \
./net/netfilter/xt_DSCP.d \
./net/netfilter/xt_HL.d \
./net/netfilter/xt_LED.d \
./net/netfilter/xt_MARK.d \
./net/netfilter/xt_NFLOG.d \
./net/netfilter/xt_NFQUEUE.d \
./net/netfilter/xt_NOTRACK.d \
./net/netfilter/xt_RATEEST.d \
./net/netfilter/xt_SECMARK.d \
./net/netfilter/xt_TCPMSS.d \
./net/netfilter/xt_TCPOPTSTRIP.d \
./net/netfilter/xt_TPROXY.d \
./net/netfilter/xt_TRACE.d \
./net/netfilter/xt_cluster.d \
./net/netfilter/xt_comment.d \
./net/netfilter/xt_connbytes.d \
./net/netfilter/xt_connlimit.d \
./net/netfilter/xt_connmark.d \
./net/netfilter/xt_conntrack.d \
./net/netfilter/xt_dccp.d \
./net/netfilter/xt_dscp.d \
./net/netfilter/xt_esp.d \
./net/netfilter/xt_hashlimit.d \
./net/netfilter/xt_helper.d \
./net/netfilter/xt_hl.d \
./net/netfilter/xt_iprange.d \
./net/netfilter/xt_length.d \
./net/netfilter/xt_limit.d \
./net/netfilter/xt_mac.d \
./net/netfilter/xt_mark.d \
./net/netfilter/xt_multiport.d \
./net/netfilter/xt_osf.d \
./net/netfilter/xt_owner.d \
./net/netfilter/xt_physdev.d \
./net/netfilter/xt_pkttype.d \
./net/netfilter/xt_policy.d \
./net/netfilter/xt_quota.d \
./net/netfilter/xt_rateest.d \
./net/netfilter/xt_realm.d \
./net/netfilter/xt_recent.d \
./net/netfilter/xt_sctp.d \
./net/netfilter/xt_socket.d \
./net/netfilter/xt_state.d \
./net/netfilter/xt_statistic.d \
./net/netfilter/xt_string.d \
./net/netfilter/xt_tcpmss.d \
./net/netfilter/xt_tcpudp.d \
./net/netfilter/xt_time.d \
./net/netfilter/xt_u32.d 


# Each subdirectory must supply rules for building sources it contributes
net/netfilter/%.o: ../net/netfilter/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


