################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
virt/kvm \
usr \
tools/perf/util \
tools/perf/util/scripting-engines \
tools/perf/scripts/python/Perf-Trace-Util \
tools/perf/scripts/perl/Perf-Trace-Util \
tools/perf \
tools/perf/bench \
sound/usb/usx2y \
sound/usb \
sound/usb/caiaq \
sound/synth \
sound/synth/emux \
sound/spi \
sound/sparc \
sound \
sound/soc/txx9 \
sound/soc \
sound/soc/sh \
sound/soc/s6000 \
sound/soc/s3c24xx \
sound/soc/pxa \
sound/soc/omap \
sound/soc/imx \
sound/soc/fsl \
sound/soc/davinci \
sound/soc/codecs \
sound/soc/blackfin \
sound/soc/au1x \
sound/soc/atmel \
sound/sh \
sound/ppc \
sound/pcmcia/vx \
sound/pcmcia/pdaudiocf \
sound/pci/ymfpci \
sound/pci/vx222 \
sound/pci \
sound/pci/trident \
sound/pci/rme9652 \
sound/pci/riptide \
sound/pci/pcxhr \
sound/pci/oxygen \
sound/pci/nm256 \
sound/pci/mixart \
sound/pci/lx6464es \
sound/pci/korg1212 \
sound/pci/ice1712 \
sound/pci/hda \
sound/pci/emu10k1 \
sound/pci/echoaudio \
sound/pci/ctxfi \
sound/pci/cs5535audio \
sound/pci/cs46xx \
sound/pci/ca0106 \
sound/pci/aw2 \
sound/pci/au88x0 \
sound/pci/ali5451 \
sound/pci/ac97 \
sound/parisc \
sound/oss \
sound/oss/dmasound \
sound/mips \
sound/isa/wss \
sound/isa/wavefront \
sound/isa \
sound/isa/sb \
sound/isa/opti9xx \
sound/isa/msnd \
sound/isa/gus \
sound/isa/es1688 \
sound/isa/cs423x \
sound/isa/ad1848 \
sound/isa/ad1816a \
sound/i2c \
sound/i2c/other \
sound/drivers/vx \
sound/drivers \
sound/drivers/pcsp \
sound/drivers/opl4 \
sound/drivers/opl3 \
sound/drivers/mpu401 \
sound/core \
sound/core/seq \
sound/core/seq/oss \
sound/core/oss \
sound/atmel \
sound/arm \
sound/aoa/soundbus \
sound/aoa/soundbus/i2sbus \
sound/aoa/fabrics \
sound/aoa/core \
sound/aoa/codecs \
security/tomoyo \
security/smack \
security/selinux \
security/selinux/ss \
security \
security/keys \
security/integrity/ima \
scripts \
scripts/selinux/mdp \
scripts/selinux/genheaders \
scripts/mod \
scripts/kconfig \
scripts/kconfig/lxdialog \
scripts/genksyms \
scripts/dtc \
scripts/dtc/libfdt \
scripts/basic \
samples/tracepoints \
samples/trace_events \
samples/kprobes \
samples/kobject \
samples/hw_breakpoint \
net/xfrm \
net/x25 \
net/wireless \
net/wimax \
net/wanrouter \
net/unix \
net/tipc \
net \
net/sunrpc \
net/sunrpc/xprtrdma \
net/sunrpc/auth_gss \
net/sctp \
net/sched \
net/rxrpc \
net/rose \
net/rfkill \
net/rds \
net/phonet \
net/packet \
net/netrom \
net/netlink \
net/netlabel \
net/netfilter \
net/netfilter/ipvs \
net/mac80211 \
net/llc \
net/lapb \
net/key \
net/iucv \
net/irda \
net/irda/irnet \
net/irda/irlan \
net/irda/ircomm \
net/ipx \
net/ipv6 \
net/ipv6/netfilter \
net/ipv4 \
net/ipv4/netfilter \
net/ieee802154 \
net/ethernet \
net/econet \
net/dsa \
net/decnet \
net/decnet/netfilter \
net/dccp \
net/dccp/ccids/lib \
net/dccp/ccids \
net/dcb \
net/core \
net/can \
net/bridge/netfilter \
net/bridge \
net/bluetooth \
net/bluetooth/rfcomm \
net/bluetooth/hidp \
net/bluetooth/cmtp \
net/bluetooth/bnep \
net/ax25 \
net/atm \
net/appletalk \
net/9p \
net/8021q \
net/802 \
mm \
lib/zlib_inflate \
lib/zlib_deflate \
lib \
lib/reed_solomon \
lib/lzo \
kernel \
kernel/trace \
kernel/time \
kernel/power \
kernel/irq \
kernel/gcov \
ipc \
init \
include/asm-generic \
fs/xfs \
fs/xfs/support \
fs/xfs/quota \
fs/xfs/linux-2.6 \
fs \
fs/ufs \
fs/udf \
fs/ubifs \
fs/sysv \
fs/sysfs \
fs/squashfs \
fs/smbfs \
fs/romfs \
fs/reiserfs \
fs/ramfs \
fs/quota \
fs/qnx4 \
fs/proc \
fs/partitions \
fs/openpromfs \
fs/omfs \
fs/ocfs2 \
fs/ocfs2/dlmfs \
fs/ocfs2/dlm \
fs/ocfs2/cluster \
fs/ntfs \
fs/notify \
fs/notify/inotify \
fs/notify/dnotify \
fs/nls \
fs/nilfs2 \
fs/nfsd \
fs/nfs_common \
fs/nfs \
fs/ncpfs \
fs/minix \
fs/logfs \
fs/lockd \
fs/jfs \
fs/jffs2 \
fs/jbd2 \
fs/jbd \
fs/isofs \
fs/hugetlbfs \
fs/hppfs \
fs/hpfs \
fs/hostfs \
fs/hfsplus \
fs/hfs \
fs/gfs2 \
fs/fuse \
fs/fscache \
fs/freevxfs \
fs/fat \
fs/ext4 \
fs/ext3 \
fs/ext2 \
fs/exportfs \
fs/exofs \
fs/efs \
fs/ecryptfs \
fs/dlm \
fs/devpts \
fs/debugfs \
fs/cramfs \
fs/configfs \
fs/coda \
fs/cifs \
fs/ceph \
fs/ceph/crush \
fs/cachefiles \
fs/btrfs \
fs/bfs \
fs/befs \
fs/autofs4 \
fs/autofs \
fs/afs \
fs/affs \
fs/adfs \
fs/9p \
firmware/keyspan_pda \
firmware \
firmware/dsp56k \
firmware/av7110 \
drivers/zorro \
drivers/xen/xenfs \
drivers/xen \
drivers/xen/xenbus \
drivers/watchdog \
drivers/w1 \
drivers/w1/slaves \
drivers/w1/masters \
drivers/vlynq \
drivers/virtio \
drivers/video \
drivers/video/via \
drivers/video/vermilion \
drivers/video/sis \
drivers/video/savage \
drivers/video/riva \
drivers/video/pnx4008 \
drivers/video/omap2 \
drivers/video/omap2/omapfb \
drivers/video/omap2/dss \
drivers/video/omap2/displays \
drivers/video/omap \
drivers/video/nvidia \
drivers/video/msm \
drivers/video/mbx \
drivers/video/mb862xx \
drivers/video/matrox \
drivers/video/logo \
drivers/video/kyro \
drivers/video/intelfb \
drivers/video/i810 \
drivers/video/geode \
drivers/video/display \
drivers/video/console \
drivers/video/backlight \
drivers/video/aty \
drivers/vhost \
drivers/uwb/wlp \
drivers/uwb \
drivers/uwb/i1480/i1480u-wlp \
drivers/uwb/i1480 \
drivers/uwb/i1480/dfu \
drivers/usb/wusbcore \
drivers/usb \
drivers/usb/storage \
drivers/usb/serial \
drivers/usb/otg \
drivers/usb/musb \
drivers/usb/mon \
drivers/usb/misc \
drivers/usb/misc/sisusbvga \
drivers/usb/image \
drivers/usb/host \
drivers/usb/host/whci \
drivers/usb/gadget \
drivers/usb/early \
drivers/usb/core \
drivers/usb/class \
drivers/usb/c67x00 \
drivers/usb/atm \
drivers/uio \
drivers/thermal \
drivers/telephony \
drivers/tc \
drivers/staging/wlan-ng \
drivers/staging/wlags49_h25 \
drivers/staging/wlags49_h2 \
drivers/staging/winbond \
drivers/staging/wavelan \
drivers/staging/vt6656 \
drivers/staging/vt6655 \
drivers/staging/vme \
drivers/staging/vme/devices \
drivers/staging/vme/bridges \
drivers/staging/vme/boards \
drivers/staging/usbip \
drivers/staging/udlfb \
drivers/staging/strip \
drivers/staging \
drivers/staging/sm7xx \
drivers/staging/slicoss \
drivers/staging/serqt_usb2 \
drivers/staging/sep \
drivers/staging/samsung-laptop \
drivers/staging/rtl8192u \
drivers/staging/rtl8192u/ieee80211 \
drivers/staging/rtl8192su \
drivers/staging/rtl8192su/ieee80211 \
drivers/staging/rtl8192e \
drivers/staging/rtl8192e/ieee80211 \
drivers/staging/rtl8187se \
drivers/staging/rtl8187se/ieee80211 \
drivers/staging/rt2870 \
drivers/staging/rt2870/sta \
drivers/staging/rt2870/common \
drivers/staging/rt2870/chips \
drivers/staging/rt2860 \
drivers/staging/rt2860/sta \
drivers/staging/rt2860/common \
drivers/staging/rt2860/chips \
drivers/staging/rar_register \
drivers/staging/ramzswap \
drivers/staging/quatech_usb2 \
drivers/staging/pohmelfs \
drivers/staging/poch \
drivers/staging/phison \
drivers/staging/panel \
drivers/staging/otus \
drivers/staging/otus/hal \
drivers/staging/otus/80211core \
drivers/staging/octeon \
drivers/staging/netwave \
drivers/staging/line6 \
drivers/staging/iio/trigger \
drivers/staging/iio \
drivers/staging/iio/light \
drivers/staging/iio/adc \
drivers/staging/iio/accel \
drivers/staging/iio/Documentation \
drivers/staging/hv \
drivers/staging/go7007 \
drivers/staging/frontier \
drivers/staging/et131x \
drivers/staging/echo \
drivers/staging/dt3155 \
drivers/staging/dream \
drivers/staging/dream/smd \
drivers/staging/dream/qdsp5 \
drivers/staging/dream/camera \
drivers/staging/cx25821 \
drivers/staging/crystalhd \
drivers/staging/comedi \
drivers/staging/comedi/kcomedilib \
drivers/staging/comedi/drivers \
drivers/staging/comedi/drivers/addi-data \
drivers/staging/batman-adv \
drivers/staging/asus_oled \
drivers/staging/arlan \
drivers/ssb \
drivers/spi \
drivers/sn \
drivers/sh/superhyway \
drivers/sh \
drivers/sh/maple \
drivers/sfi \
drivers/serial \
drivers/serial/jsm \
drivers/serial/cpm_uart \
drivers/scsi \
drivers/scsi/sym53c8xx_2 \
drivers/scsi/qla4xxx \
drivers/scsi/qla2xxx \
drivers/scsi/pm8001 \
drivers/scsi/pcmcia \
drivers/scsi/osd \
drivers/scsi/mvsas \
drivers/scsi/mpt2sas \
drivers/scsi/megaraid \
drivers/scsi/lpfc \
drivers/scsi/libsas \
drivers/scsi/libfc \
drivers/scsi/ibmvscsi \
drivers/scsi/fnic \
drivers/scsi/fcoe \
drivers/scsi/device_handler \
drivers/scsi/cxgb3i \
drivers/scsi/bnx2i \
drivers/scsi/bfa \
drivers/scsi/be2iscsi \
drivers/scsi/arm \
drivers/scsi/arcmsr \
drivers/scsi/aic94xx \
drivers/scsi/aic7xxx_old \
drivers/scsi/aic7xxx \
drivers/scsi/aic7xxx/aicasm \
drivers/scsi/aacraid \
drivers/sbus/char \
drivers/s390/scsi \
drivers/s390/net \
drivers/s390/kvm \
drivers/s390/crypto \
drivers/s390/cio \
drivers/s390/char \
drivers/s390/block \
drivers/rtc \
drivers/regulator \
drivers/rapidio/switches \
drivers/rapidio \
drivers/ps3 \
drivers/pps \
drivers/pps/clients \
drivers/power \
drivers/pnp \
drivers/pnp/pnpbios \
drivers/pnp/pnpacpi \
drivers/pnp/isapnp \
drivers/platform/x86 \
drivers/platform \
drivers/pcmcia \
drivers/pci \
drivers/pci/pcie \
drivers/pci/pcie/pme \
drivers/pci/pcie/aer \
drivers/pci/hotplug \
drivers/parport \
drivers/parisc \
drivers/oprofile \
drivers/of \
drivers/nubus \
drivers/net \
drivers/net/wireless/zd1211rw \
drivers/net/wireless \
drivers/net/wireless/wl12xx \
drivers/net/wireless/rtl818x \
drivers/net/wireless/rt2x00 \
drivers/net/wireless/prism54 \
drivers/net/wireless/p54 \
drivers/net/wireless/orinoco \
drivers/net/wireless/libertas_tf \
drivers/net/wireless/libertas \
drivers/net/wireless/iwmc3200wifi \
drivers/net/wireless/iwlwifi \
drivers/net/wireless/ipw2x00 \
drivers/net/wireless/hostap \
drivers/net/wireless/b43legacy \
drivers/net/wireless/b43 \
drivers/net/wireless/ath \
drivers/net/wireless/ath/ath9k \
drivers/net/wireless/ath/ath5k \
drivers/net/wireless/ath/ar9170 \
drivers/net/wimax/i2400m \
drivers/net/wan \
drivers/net/wan/lmc \
drivers/net/vxge \
drivers/net/vmxnet3 \
drivers/net/usb \
drivers/net/tulip \
drivers/net/tokenring \
drivers/net/stmmac \
drivers/net/skfp \
drivers/net/sfc \
drivers/net/qlge \
drivers/net/qlcnic \
drivers/net/phy \
drivers/net/pcmcia \
drivers/net/octeon \
drivers/net/netxen \
drivers/net/myri10ge \
drivers/net/mlx4 \
drivers/net/ixp2000 \
drivers/net/ixgbevf \
drivers/net/ixgbe \
drivers/net/ixgb \
drivers/net/irda \
drivers/net/igbvf \
drivers/net/igb \
drivers/net/ibm_newemac \
drivers/net/hamradio \
drivers/net/fs_enet \
drivers/net/enic \
drivers/net/ehea \
drivers/net/e1000e \
drivers/net/e1000 \
drivers/net/cxgb4 \
drivers/net/cxgb3 \
drivers/net/cris \
drivers/net/chelsio \
drivers/net/can \
drivers/net/can/usb \
drivers/net/can/sja1000 \
drivers/net/can/mscan \
drivers/net/bonding \
drivers/net/benet \
drivers/net/atlx \
drivers/net/atl1e \
drivers/net/atl1c \
drivers/net/arm \
drivers/net/arcnet \
drivers/net/appletalk \
drivers/mtd/ubi \
drivers/mtd/tests \
drivers/mtd \
drivers/mtd/onenand \
drivers/mtd/nand \
drivers/mtd/maps \
drivers/mtd/lpddr \
drivers/mtd/devices \
drivers/mtd/chips \
drivers/mmc/host \
drivers/mmc/core \
drivers/mmc/card \
drivers/misc \
drivers/misc/sgi-xp \
drivers/misc/sgi-gru \
drivers/misc/iwmc3200top \
drivers/misc/ibmasm \
drivers/misc/hdpuftrs \
drivers/misc/eeprom \
drivers/misc/cb710 \
drivers/misc/c2port \
drivers/mfd \
drivers/message/i2o \
drivers/message/fusion \
drivers/memstick/host \
drivers/memstick/core \
drivers/media/video \
drivers/media/video/zoran \
drivers/media/video/zc0301 \
drivers/media/video/uvc \
drivers/media/video/usbvision \
drivers/media/video/usbvideo \
drivers/media/video/tlg2300 \
drivers/media/video/sn9c102 \
drivers/media/video/saa7164 \
drivers/media/video/saa7134 \
drivers/media/video/pwc \
drivers/media/video/pvrusb2 \
drivers/media/video/ovcamchip \
drivers/media/video/ivtv \
drivers/media/video/hdpvr \
drivers/media/video/gspca \
drivers/media/video/gspca/stv06xx \
drivers/media/video/gspca/m5602 \
drivers/media/video/gspca/gl860 \
drivers/media/video/et61x251 \
drivers/media/video/em28xx \
drivers/media/video/davinci \
drivers/media/video/cx88 \
drivers/media/video/cx25840 \
drivers/media/video/cx23885 \
drivers/media/video/cx231xx \
drivers/media/video/cx18 \
drivers/media/video/cpia2 \
drivers/media/video/bt8xx \
drivers/media/video/au0828 \
drivers/media/radio \
drivers/media/radio/si470x \
drivers/media/dvb/ttusb-dec \
drivers/media/dvb/ttusb-budget \
drivers/media/dvb/ttpci \
drivers/media/dvb/siano \
drivers/media/dvb/pt1 \
drivers/media/dvb/pluto2 \
drivers/media/dvb/ngene \
drivers/media/dvb/mantis \
drivers/media/dvb/frontends \
drivers/media/dvb/firewire \
drivers/media/dvb/dvb-usb \
drivers/media/dvb/dvb-core \
drivers/media/dvb/dm1105 \
drivers/media/dvb/bt8xx \
drivers/media/dvb/b2c2 \
drivers/media/common/tuners \
drivers/media/common \
drivers/media \
drivers/media/IR \
drivers/md/raid6test \
drivers/md \
drivers/mca \
drivers/macintosh \
drivers/lguest/x86 \
drivers/lguest \
drivers/leds \
drivers/isdn/sc \
drivers/isdn/pcbit \
drivers/isdn/mISDN \
drivers/isdn/isdnloop \
drivers/isdn/icn \
drivers/isdn/i4l \
drivers/isdn/hysdn \
drivers/isdn/hisax \
drivers/isdn/hardware/mISDN \
drivers/isdn/hardware/eicon \
drivers/isdn/hardware/avm \
drivers/isdn/gigaset \
drivers/isdn/divert \
drivers/isdn/capi \
drivers/isdn/act2000 \
drivers/input \
drivers/input/touchscreen \
drivers/input/tablet \
drivers/input/serio \
drivers/input/mouse \
drivers/input/misc \
drivers/input/keyboard \
drivers/input/joystick \
drivers/input/joystick/iforce \
drivers/input/gameport \
drivers/infiniband/ulp/srp \
drivers/infiniband/ulp/iser \
drivers/infiniband/ulp/ipoib \
drivers/infiniband/hw/nes \
drivers/infiniband/hw/mthca \
drivers/infiniband/hw/mlx4 \
drivers/infiniband/hw/ipath \
drivers/infiniband/hw/ehca \
drivers/infiniband/hw/cxgb3 \
drivers/infiniband/hw/amso1100 \
drivers/infiniband/core \
drivers/ieee802154 \
drivers/ieee1394 \
drivers/idle \
drivers/ide \
drivers/i2c \
drivers/i2c/busses \
drivers/i2c/algos \
drivers/hwmon \
drivers/hwmon/ams \
drivers/hid/usbhid \
drivers/hid \
drivers/gpu/vga \
drivers/gpu/drm/vmwgfx \
drivers/gpu/drm/via \
drivers/gpu/drm/ttm \
drivers/gpu/drm/tdfx \
drivers/gpu/drm/sis \
drivers/gpu/drm/savage \
drivers/gpu/drm/radeon \
drivers/gpu/drm/r128 \
drivers/gpu/drm/nouveau \
drivers/gpu/drm/mga \
drivers/gpu/drm/i915 \
drivers/gpu/drm/i830 \
drivers/gpu/drm/i810 \
drivers/gpu/drm/i2c \
drivers/gpu/drm \
drivers/gpu \
drivers/gpio \
drivers/firmware \
drivers/firewire \
drivers/eisa \
drivers/edac \
drivers/dma \
drivers/dma/ppc4xx \
drivers/dma/ipu \
drivers/dma/ioat \
drivers/dio \
drivers/dca \
drivers/crypto \
drivers/crypto/amcc \
drivers/cpuidle \
drivers/cpuidle/governors \
drivers/cpufreq \
drivers/connector \
drivers/clocksource \
drivers/char/xilinx_hwicap \
drivers/char \
drivers/char/tpm \
drivers/char/rio \
drivers/char/pcmcia \
drivers/char/pcmcia/ipwireless \
drivers/char/mwave \
drivers/char/ipmi \
drivers/char/ip2 \
drivers/char/hw_random \
drivers/char/agp \
drivers/cdrom \
drivers \
drivers/bluetooth \
drivers/block \
drivers/block/paride \
drivers/block/drbd \
drivers/block/aoe \
drivers/base \
drivers/base/power \
drivers/auxdisplay \
drivers/atm \
drivers/ata \
drivers/amba \
drivers/acpi \
drivers/acpi/acpica \
drivers/accessibility/braille \
crypto \
crypto/async_tx \
block \
arch/x86/xen \
arch/x86/video \
arch/x86/vdso \
arch/x86/vdso/vdso32 \
arch/x86/tools \
arch/x86/power \
arch/x86/pci \
arch/x86/oprofile \
arch/x86/mm \
arch/x86/mm/kmemcheck \
arch/x86/math-emu \
arch/x86/lib \
arch/x86/lguest \
arch/x86/kvm \
arch/x86/kernel \
arch/x86/kernel/cpu \
arch/x86/kernel/cpu/mtrr \
arch/x86/kernel/cpu/mcheck \
arch/x86/kernel/cpu/cpufreq \
arch/x86/kernel/apic \
arch/x86/kernel/acpi \
arch/x86/kernel/acpi/realmode \
arch/x86/ia32 \
arch/x86/crypto \
arch/x86 \
arch/x86/boot \
arch/x86/boot/tools \
arch/x86/boot/compressed \
Documentation/watchdog/src \
Documentation/vm \
Documentation/video4linux \
Documentation/timers \
Documentation/spi \
Documentation/prctl \
Documentation/pcmcia \
Documentation/networking/timestamping \
Documentation/networking \
Documentation/lguest \
Documentation/laptops \
Documentation/ia64 \
Documentation/hwmon \
Documentation/filesystems \
Documentation/filesystems/configfs \
Documentation/connector \
Documentation/cgroups \
Documentation/blackfin \
Documentation/auxdisplay \
Documentation/accounting \

