################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/hwmon/built-in.o \
../drivers/hwmon/hwmon.o 

C_SRCS += \
../drivers/hwmon/abituguru.c \
../drivers/hwmon/abituguru3.c \
../drivers/hwmon/ad7414.c \
../drivers/hwmon/ad7418.c \
../drivers/hwmon/adcxx.c \
../drivers/hwmon/adm1021.c \
../drivers/hwmon/adm1025.c \
../drivers/hwmon/adm1026.c \
../drivers/hwmon/adm1029.c \
../drivers/hwmon/adm1031.c \
../drivers/hwmon/adm9240.c \
../drivers/hwmon/ads7828.c \
../drivers/hwmon/adt7411.c \
../drivers/hwmon/adt7462.c \
../drivers/hwmon/adt7470.c \
../drivers/hwmon/adt7475.c \
../drivers/hwmon/amc6821.c \
../drivers/hwmon/applesmc.c \
../drivers/hwmon/asb100.c \
../drivers/hwmon/asc7621.c \
../drivers/hwmon/asus_atk0110.c \
../drivers/hwmon/atxp1.c \
../drivers/hwmon/coretemp.c \
../drivers/hwmon/dme1737.c \
../drivers/hwmon/ds1621.c \
../drivers/hwmon/f71805f.c \
../drivers/hwmon/f71882fg.c \
../drivers/hwmon/f75375s.c \
../drivers/hwmon/fschmd.c \
../drivers/hwmon/g760a.c \
../drivers/hwmon/gl518sm.c \
../drivers/hwmon/gl520sm.c \
../drivers/hwmon/hdaps.c \
../drivers/hwmon/hp_accel.c \
../drivers/hwmon/hwmon-vid.c \
../drivers/hwmon/hwmon.c \
../drivers/hwmon/i5k_amb.c \
../drivers/hwmon/ibmaem.c \
../drivers/hwmon/ibmpex.c \
../drivers/hwmon/it87.c \
../drivers/hwmon/k10temp.c \
../drivers/hwmon/k8temp.c \
../drivers/hwmon/lis3lv02d.c \
../drivers/hwmon/lis3lv02d_i2c.c \
../drivers/hwmon/lis3lv02d_spi.c \
../drivers/hwmon/lm63.c \
../drivers/hwmon/lm70.c \
../drivers/hwmon/lm73.c \
../drivers/hwmon/lm75.c \
../drivers/hwmon/lm77.c \
../drivers/hwmon/lm78.c \
../drivers/hwmon/lm80.c \
../drivers/hwmon/lm83.c \
../drivers/hwmon/lm85.c \
../drivers/hwmon/lm87.c \
../drivers/hwmon/lm90.c \
../drivers/hwmon/lm92.c \
../drivers/hwmon/lm93.c \
../drivers/hwmon/lm95241.c \
../drivers/hwmon/ltc4215.c \
../drivers/hwmon/ltc4245.c \
../drivers/hwmon/max1111.c \
../drivers/hwmon/max1619.c \
../drivers/hwmon/max6650.c \
../drivers/hwmon/mc13783-adc.c \
../drivers/hwmon/pc87360.c \
../drivers/hwmon/pc87427.c \
../drivers/hwmon/pcf8591.c \
../drivers/hwmon/s3c-hwmon.c \
../drivers/hwmon/sht15.c \
../drivers/hwmon/sis5595.c \
../drivers/hwmon/smsc47b397.c \
../drivers/hwmon/smsc47m1.c \
../drivers/hwmon/smsc47m192.c \
../drivers/hwmon/thmc50.c \
../drivers/hwmon/tmp401.c \
../drivers/hwmon/tmp421.c \
../drivers/hwmon/ultra45_env.c \
../drivers/hwmon/via-cputemp.c \
../drivers/hwmon/via686a.c \
../drivers/hwmon/vt1211.c \
../drivers/hwmon/vt8231.c \
../drivers/hwmon/w83627ehf.c \
../drivers/hwmon/w83627hf.c \
../drivers/hwmon/w83781d.c \
../drivers/hwmon/w83791d.c \
../drivers/hwmon/w83792d.c \
../drivers/hwmon/w83793.c \
../drivers/hwmon/w83l785ts.c \
../drivers/hwmon/w83l786ng.c \
../drivers/hwmon/wm831x-hwmon.c \
../drivers/hwmon/wm8350-hwmon.c 

OBJS += \
./drivers/hwmon/abituguru.o \
./drivers/hwmon/abituguru3.o \
./drivers/hwmon/ad7414.o \
./drivers/hwmon/ad7418.o \
./drivers/hwmon/adcxx.o \
./drivers/hwmon/adm1021.o \
./drivers/hwmon/adm1025.o \
./drivers/hwmon/adm1026.o \
./drivers/hwmon/adm1029.o \
./drivers/hwmon/adm1031.o \
./drivers/hwmon/adm9240.o \
./drivers/hwmon/ads7828.o \
./drivers/hwmon/adt7411.o \
./drivers/hwmon/adt7462.o \
./drivers/hwmon/adt7470.o \
./drivers/hwmon/adt7475.o \
./drivers/hwmon/amc6821.o \
./drivers/hwmon/applesmc.o \
./drivers/hwmon/asb100.o \
./drivers/hwmon/asc7621.o \
./drivers/hwmon/asus_atk0110.o \
./drivers/hwmon/atxp1.o \
./drivers/hwmon/coretemp.o \
./drivers/hwmon/dme1737.o \
./drivers/hwmon/ds1621.o \
./drivers/hwmon/f71805f.o \
./drivers/hwmon/f71882fg.o \
./drivers/hwmon/f75375s.o \
./drivers/hwmon/fschmd.o \
./drivers/hwmon/g760a.o \
./drivers/hwmon/gl518sm.o \
./drivers/hwmon/gl520sm.o \
./drivers/hwmon/hdaps.o \
./drivers/hwmon/hp_accel.o \
./drivers/hwmon/hwmon-vid.o \
./drivers/hwmon/hwmon.o \
./drivers/hwmon/i5k_amb.o \
./drivers/hwmon/ibmaem.o \
./drivers/hwmon/ibmpex.o \
./drivers/hwmon/it87.o \
./drivers/hwmon/k10temp.o \
./drivers/hwmon/k8temp.o \
./drivers/hwmon/lis3lv02d.o \
./drivers/hwmon/lis3lv02d_i2c.o \
./drivers/hwmon/lis3lv02d_spi.o \
./drivers/hwmon/lm63.o \
./drivers/hwmon/lm70.o \
./drivers/hwmon/lm73.o \
./drivers/hwmon/lm75.o \
./drivers/hwmon/lm77.o \
./drivers/hwmon/lm78.o \
./drivers/hwmon/lm80.o \
./drivers/hwmon/lm83.o \
./drivers/hwmon/lm85.o \
./drivers/hwmon/lm87.o \
./drivers/hwmon/lm90.o \
./drivers/hwmon/lm92.o \
./drivers/hwmon/lm93.o \
./drivers/hwmon/lm95241.o \
./drivers/hwmon/ltc4215.o \
./drivers/hwmon/ltc4245.o \
./drivers/hwmon/max1111.o \
./drivers/hwmon/max1619.o \
./drivers/hwmon/max6650.o \
./drivers/hwmon/mc13783-adc.o \
./drivers/hwmon/pc87360.o \
./drivers/hwmon/pc87427.o \
./drivers/hwmon/pcf8591.o \
./drivers/hwmon/s3c-hwmon.o \
./drivers/hwmon/sht15.o \
./drivers/hwmon/sis5595.o \
./drivers/hwmon/smsc47b397.o \
./drivers/hwmon/smsc47m1.o \
./drivers/hwmon/smsc47m192.o \
./drivers/hwmon/thmc50.o \
./drivers/hwmon/tmp401.o \
./drivers/hwmon/tmp421.o \
./drivers/hwmon/ultra45_env.o \
./drivers/hwmon/via-cputemp.o \
./drivers/hwmon/via686a.o \
./drivers/hwmon/vt1211.o \
./drivers/hwmon/vt8231.o \
./drivers/hwmon/w83627ehf.o \
./drivers/hwmon/w83627hf.o \
./drivers/hwmon/w83781d.o \
./drivers/hwmon/w83791d.o \
./drivers/hwmon/w83792d.o \
./drivers/hwmon/w83793.o \
./drivers/hwmon/w83l785ts.o \
./drivers/hwmon/w83l786ng.o \
./drivers/hwmon/wm831x-hwmon.o \
./drivers/hwmon/wm8350-hwmon.o 

C_DEPS += \
./drivers/hwmon/abituguru.d \
./drivers/hwmon/abituguru3.d \
./drivers/hwmon/ad7414.d \
./drivers/hwmon/ad7418.d \
./drivers/hwmon/adcxx.d \
./drivers/hwmon/adm1021.d \
./drivers/hwmon/adm1025.d \
./drivers/hwmon/adm1026.d \
./drivers/hwmon/adm1029.d \
./drivers/hwmon/adm1031.d \
./drivers/hwmon/adm9240.d \
./drivers/hwmon/ads7828.d \
./drivers/hwmon/adt7411.d \
./drivers/hwmon/adt7462.d \
./drivers/hwmon/adt7470.d \
./drivers/hwmon/adt7475.d \
./drivers/hwmon/amc6821.d \
./drivers/hwmon/applesmc.d \
./drivers/hwmon/asb100.d \
./drivers/hwmon/asc7621.d \
./drivers/hwmon/asus_atk0110.d \
./drivers/hwmon/atxp1.d \
./drivers/hwmon/coretemp.d \
./drivers/hwmon/dme1737.d \
./drivers/hwmon/ds1621.d \
./drivers/hwmon/f71805f.d \
./drivers/hwmon/f71882fg.d \
./drivers/hwmon/f75375s.d \
./drivers/hwmon/fschmd.d \
./drivers/hwmon/g760a.d \
./drivers/hwmon/gl518sm.d \
./drivers/hwmon/gl520sm.d \
./drivers/hwmon/hdaps.d \
./drivers/hwmon/hp_accel.d \
./drivers/hwmon/hwmon-vid.d \
./drivers/hwmon/hwmon.d \
./drivers/hwmon/i5k_amb.d \
./drivers/hwmon/ibmaem.d \
./drivers/hwmon/ibmpex.d \
./drivers/hwmon/it87.d \
./drivers/hwmon/k10temp.d \
./drivers/hwmon/k8temp.d \
./drivers/hwmon/lis3lv02d.d \
./drivers/hwmon/lis3lv02d_i2c.d \
./drivers/hwmon/lis3lv02d_spi.d \
./drivers/hwmon/lm63.d \
./drivers/hwmon/lm70.d \
./drivers/hwmon/lm73.d \
./drivers/hwmon/lm75.d \
./drivers/hwmon/lm77.d \
./drivers/hwmon/lm78.d \
./drivers/hwmon/lm80.d \
./drivers/hwmon/lm83.d \
./drivers/hwmon/lm85.d \
./drivers/hwmon/lm87.d \
./drivers/hwmon/lm90.d \
./drivers/hwmon/lm92.d \
./drivers/hwmon/lm93.d \
./drivers/hwmon/lm95241.d \
./drivers/hwmon/ltc4215.d \
./drivers/hwmon/ltc4245.d \
./drivers/hwmon/max1111.d \
./drivers/hwmon/max1619.d \
./drivers/hwmon/max6650.d \
./drivers/hwmon/mc13783-adc.d \
./drivers/hwmon/pc87360.d \
./drivers/hwmon/pc87427.d \
./drivers/hwmon/pcf8591.d \
./drivers/hwmon/s3c-hwmon.d \
./drivers/hwmon/sht15.d \
./drivers/hwmon/sis5595.d \
./drivers/hwmon/smsc47b397.d \
./drivers/hwmon/smsc47m1.d \
./drivers/hwmon/smsc47m192.d \
./drivers/hwmon/thmc50.d \
./drivers/hwmon/tmp401.d \
./drivers/hwmon/tmp421.d \
./drivers/hwmon/ultra45_env.d \
./drivers/hwmon/via-cputemp.d \
./drivers/hwmon/via686a.d \
./drivers/hwmon/vt1211.d \
./drivers/hwmon/vt8231.d \
./drivers/hwmon/w83627ehf.d \
./drivers/hwmon/w83627hf.d \
./drivers/hwmon/w83781d.d \
./drivers/hwmon/w83791d.d \
./drivers/hwmon/w83792d.d \
./drivers/hwmon/w83793.d \
./drivers/hwmon/w83l785ts.d \
./drivers/hwmon/w83l786ng.d \
./drivers/hwmon/wm831x-hwmon.d \
./drivers/hwmon/wm8350-hwmon.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/hwmon/%.o: ../drivers/hwmon/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


