################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/rtc/class.c \
../drivers/rtc/hctosys.c \
../drivers/rtc/interface.c \
../drivers/rtc/rtc-ab3100.c \
../drivers/rtc/rtc-at32ap700x.c \
../drivers/rtc/rtc-at91rm9200.c \
../drivers/rtc/rtc-at91sam9.c \
../drivers/rtc/rtc-au1xxx.c \
../drivers/rtc/rtc-bfin.c \
../drivers/rtc/rtc-bq32k.c \
../drivers/rtc/rtc-bq4802.c \
../drivers/rtc/rtc-cmos.c \
../drivers/rtc/rtc-coh901331.c \
../drivers/rtc/rtc-dev.c \
../drivers/rtc/rtc-dm355evm.c \
../drivers/rtc/rtc-ds1216.c \
../drivers/rtc/rtc-ds1286.c \
../drivers/rtc/rtc-ds1302.c \
../drivers/rtc/rtc-ds1305.c \
../drivers/rtc/rtc-ds1307.c \
../drivers/rtc/rtc-ds1374.c \
../drivers/rtc/rtc-ds1390.c \
../drivers/rtc/rtc-ds1511.c \
../drivers/rtc/rtc-ds1553.c \
../drivers/rtc/rtc-ds1672.c \
../drivers/rtc/rtc-ds1742.c \
../drivers/rtc/rtc-ds3234.c \
../drivers/rtc/rtc-efi.c \
../drivers/rtc/rtc-ep93xx.c \
../drivers/rtc/rtc-fm3130.c \
../drivers/rtc/rtc-generic.c \
../drivers/rtc/rtc-isl1208.c \
../drivers/rtc/rtc-lib.c \
../drivers/rtc/rtc-m41t80.c \
../drivers/rtc/rtc-m41t94.c \
../drivers/rtc/rtc-m48t35.c \
../drivers/rtc/rtc-m48t59.c \
../drivers/rtc/rtc-m48t86.c \
../drivers/rtc/rtc-max6900.c \
../drivers/rtc/rtc-max6902.c \
../drivers/rtc/rtc-max8925.c \
../drivers/rtc/rtc-mc13783.c \
../drivers/rtc/rtc-mpc5121.c \
../drivers/rtc/rtc-msm6242.c \
../drivers/rtc/rtc-mv.c \
../drivers/rtc/rtc-mxc.c \
../drivers/rtc/rtc-nuc900.c \
../drivers/rtc/rtc-omap.c \
../drivers/rtc/rtc-pcap.c \
../drivers/rtc/rtc-pcf2123.c \
../drivers/rtc/rtc-pcf50633.c \
../drivers/rtc/rtc-pcf8563.c \
../drivers/rtc/rtc-pcf8583.c \
../drivers/rtc/rtc-pl030.c \
../drivers/rtc/rtc-pl031.c \
../drivers/rtc/rtc-proc.c \
../drivers/rtc/rtc-ps3.c \
../drivers/rtc/rtc-pxa.c \
../drivers/rtc/rtc-r9701.c \
../drivers/rtc/rtc-rp5c01.c \
../drivers/rtc/rtc-rs5c313.c \
../drivers/rtc/rtc-rs5c348.c \
../drivers/rtc/rtc-rs5c372.c \
../drivers/rtc/rtc-rx8025.c \
../drivers/rtc/rtc-rx8581.c \
../drivers/rtc/rtc-s35390a.c \
../drivers/rtc/rtc-s3c.c \
../drivers/rtc/rtc-sa1100.c \
../drivers/rtc/rtc-sh.c \
../drivers/rtc/rtc-starfire.c \
../drivers/rtc/rtc-stk17ta8.c \
../drivers/rtc/rtc-stmp3xxx.c \
../drivers/rtc/rtc-sun4v.c \
../drivers/rtc/rtc-sysfs.c \
../drivers/rtc/rtc-test.c \
../drivers/rtc/rtc-twl.c \
../drivers/rtc/rtc-tx4939.c \
../drivers/rtc/rtc-v3020.c \
../drivers/rtc/rtc-vr41xx.c \
../drivers/rtc/rtc-wm831x.c \
../drivers/rtc/rtc-wm8350.c \
../drivers/rtc/rtc-x1205.c 

OBJS += \
./drivers/rtc/class.o \
./drivers/rtc/hctosys.o \
./drivers/rtc/interface.o \
./drivers/rtc/rtc-ab3100.o \
./drivers/rtc/rtc-at32ap700x.o \
./drivers/rtc/rtc-at91rm9200.o \
./drivers/rtc/rtc-at91sam9.o \
./drivers/rtc/rtc-au1xxx.o \
./drivers/rtc/rtc-bfin.o \
./drivers/rtc/rtc-bq32k.o \
./drivers/rtc/rtc-bq4802.o \
./drivers/rtc/rtc-cmos.o \
./drivers/rtc/rtc-coh901331.o \
./drivers/rtc/rtc-dev.o \
./drivers/rtc/rtc-dm355evm.o \
./drivers/rtc/rtc-ds1216.o \
./drivers/rtc/rtc-ds1286.o \
./drivers/rtc/rtc-ds1302.o \
./drivers/rtc/rtc-ds1305.o \
./drivers/rtc/rtc-ds1307.o \
./drivers/rtc/rtc-ds1374.o \
./drivers/rtc/rtc-ds1390.o \
./drivers/rtc/rtc-ds1511.o \
./drivers/rtc/rtc-ds1553.o \
./drivers/rtc/rtc-ds1672.o \
./drivers/rtc/rtc-ds1742.o \
./drivers/rtc/rtc-ds3234.o \
./drivers/rtc/rtc-efi.o \
./drivers/rtc/rtc-ep93xx.o \
./drivers/rtc/rtc-fm3130.o \
./drivers/rtc/rtc-generic.o \
./drivers/rtc/rtc-isl1208.o \
./drivers/rtc/rtc-lib.o \
./drivers/rtc/rtc-m41t80.o \
./drivers/rtc/rtc-m41t94.o \
./drivers/rtc/rtc-m48t35.o \
./drivers/rtc/rtc-m48t59.o \
./drivers/rtc/rtc-m48t86.o \
./drivers/rtc/rtc-max6900.o \
./drivers/rtc/rtc-max6902.o \
./drivers/rtc/rtc-max8925.o \
./drivers/rtc/rtc-mc13783.o \
./drivers/rtc/rtc-mpc5121.o \
./drivers/rtc/rtc-msm6242.o \
./drivers/rtc/rtc-mv.o \
./drivers/rtc/rtc-mxc.o \
./drivers/rtc/rtc-nuc900.o \
./drivers/rtc/rtc-omap.o \
./drivers/rtc/rtc-pcap.o \
./drivers/rtc/rtc-pcf2123.o \
./drivers/rtc/rtc-pcf50633.o \
./drivers/rtc/rtc-pcf8563.o \
./drivers/rtc/rtc-pcf8583.o \
./drivers/rtc/rtc-pl030.o \
./drivers/rtc/rtc-pl031.o \
./drivers/rtc/rtc-proc.o \
./drivers/rtc/rtc-ps3.o \
./drivers/rtc/rtc-pxa.o \
./drivers/rtc/rtc-r9701.o \
./drivers/rtc/rtc-rp5c01.o \
./drivers/rtc/rtc-rs5c313.o \
./drivers/rtc/rtc-rs5c348.o \
./drivers/rtc/rtc-rs5c372.o \
./drivers/rtc/rtc-rx8025.o \
./drivers/rtc/rtc-rx8581.o \
./drivers/rtc/rtc-s35390a.o \
./drivers/rtc/rtc-s3c.o \
./drivers/rtc/rtc-sa1100.o \
./drivers/rtc/rtc-sh.o \
./drivers/rtc/rtc-starfire.o \
./drivers/rtc/rtc-stk17ta8.o \
./drivers/rtc/rtc-stmp3xxx.o \
./drivers/rtc/rtc-sun4v.o \
./drivers/rtc/rtc-sysfs.o \
./drivers/rtc/rtc-test.o \
./drivers/rtc/rtc-twl.o \
./drivers/rtc/rtc-tx4939.o \
./drivers/rtc/rtc-v3020.o \
./drivers/rtc/rtc-vr41xx.o \
./drivers/rtc/rtc-wm831x.o \
./drivers/rtc/rtc-wm8350.o \
./drivers/rtc/rtc-x1205.o 

C_DEPS += \
./drivers/rtc/class.d \
./drivers/rtc/hctosys.d \
./drivers/rtc/interface.d \
./drivers/rtc/rtc-ab3100.d \
./drivers/rtc/rtc-at32ap700x.d \
./drivers/rtc/rtc-at91rm9200.d \
./drivers/rtc/rtc-at91sam9.d \
./drivers/rtc/rtc-au1xxx.d \
./drivers/rtc/rtc-bfin.d \
./drivers/rtc/rtc-bq32k.d \
./drivers/rtc/rtc-bq4802.d \
./drivers/rtc/rtc-cmos.d \
./drivers/rtc/rtc-coh901331.d \
./drivers/rtc/rtc-dev.d \
./drivers/rtc/rtc-dm355evm.d \
./drivers/rtc/rtc-ds1216.d \
./drivers/rtc/rtc-ds1286.d \
./drivers/rtc/rtc-ds1302.d \
./drivers/rtc/rtc-ds1305.d \
./drivers/rtc/rtc-ds1307.d \
./drivers/rtc/rtc-ds1374.d \
./drivers/rtc/rtc-ds1390.d \
./drivers/rtc/rtc-ds1511.d \
./drivers/rtc/rtc-ds1553.d \
./drivers/rtc/rtc-ds1672.d \
./drivers/rtc/rtc-ds1742.d \
./drivers/rtc/rtc-ds3234.d \
./drivers/rtc/rtc-efi.d \
./drivers/rtc/rtc-ep93xx.d \
./drivers/rtc/rtc-fm3130.d \
./drivers/rtc/rtc-generic.d \
./drivers/rtc/rtc-isl1208.d \
./drivers/rtc/rtc-lib.d \
./drivers/rtc/rtc-m41t80.d \
./drivers/rtc/rtc-m41t94.d \
./drivers/rtc/rtc-m48t35.d \
./drivers/rtc/rtc-m48t59.d \
./drivers/rtc/rtc-m48t86.d \
./drivers/rtc/rtc-max6900.d \
./drivers/rtc/rtc-max6902.d \
./drivers/rtc/rtc-max8925.d \
./drivers/rtc/rtc-mc13783.d \
./drivers/rtc/rtc-mpc5121.d \
./drivers/rtc/rtc-msm6242.d \
./drivers/rtc/rtc-mv.d \
./drivers/rtc/rtc-mxc.d \
./drivers/rtc/rtc-nuc900.d \
./drivers/rtc/rtc-omap.d \
./drivers/rtc/rtc-pcap.d \
./drivers/rtc/rtc-pcf2123.d \
./drivers/rtc/rtc-pcf50633.d \
./drivers/rtc/rtc-pcf8563.d \
./drivers/rtc/rtc-pcf8583.d \
./drivers/rtc/rtc-pl030.d \
./drivers/rtc/rtc-pl031.d \
./drivers/rtc/rtc-proc.d \
./drivers/rtc/rtc-ps3.d \
./drivers/rtc/rtc-pxa.d \
./drivers/rtc/rtc-r9701.d \
./drivers/rtc/rtc-rp5c01.d \
./drivers/rtc/rtc-rs5c313.d \
./drivers/rtc/rtc-rs5c348.d \
./drivers/rtc/rtc-rs5c372.d \
./drivers/rtc/rtc-rx8025.d \
./drivers/rtc/rtc-rx8581.d \
./drivers/rtc/rtc-s35390a.d \
./drivers/rtc/rtc-s3c.d \
./drivers/rtc/rtc-sa1100.d \
./drivers/rtc/rtc-sh.d \
./drivers/rtc/rtc-starfire.d \
./drivers/rtc/rtc-stk17ta8.d \
./drivers/rtc/rtc-stmp3xxx.d \
./drivers/rtc/rtc-sun4v.d \
./drivers/rtc/rtc-sysfs.d \
./drivers/rtc/rtc-test.d \
./drivers/rtc/rtc-twl.d \
./drivers/rtc/rtc-tx4939.d \
./drivers/rtc/rtc-v3020.d \
./drivers/rtc/rtc-vr41xx.d \
./drivers/rtc/rtc-wm831x.d \
./drivers/rtc/rtc-wm8350.d \
./drivers/rtc/rtc-x1205.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/rtc/%.o: ../drivers/rtc/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


