################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/media/dvb/frontends/af9013.c \
../drivers/media/dvb/frontends/atbm8830.c \
../drivers/media/dvb/frontends/au8522_decoder.c \
../drivers/media/dvb/frontends/au8522_dig.c \
../drivers/media/dvb/frontends/bcm3510.c \
../drivers/media/dvb/frontends/cx22700.c \
../drivers/media/dvb/frontends/cx22702.c \
../drivers/media/dvb/frontends/cx24110.c \
../drivers/media/dvb/frontends/cx24113.c \
../drivers/media/dvb/frontends/cx24116.c \
../drivers/media/dvb/frontends/cx24123.c \
../drivers/media/dvb/frontends/dib0070.c \
../drivers/media/dvb/frontends/dib0090.c \
../drivers/media/dvb/frontends/dib3000mb.c \
../drivers/media/dvb/frontends/dib3000mc.c \
../drivers/media/dvb/frontends/dib7000m.c \
../drivers/media/dvb/frontends/dib7000p.c \
../drivers/media/dvb/frontends/dib8000.c \
../drivers/media/dvb/frontends/dibx000_common.c \
../drivers/media/dvb/frontends/drx397xD.c \
../drivers/media/dvb/frontends/ds3000.c \
../drivers/media/dvb/frontends/dvb-pll.c \
../drivers/media/dvb/frontends/dvb_dummy_fe.c \
../drivers/media/dvb/frontends/ec100.c \
../drivers/media/dvb/frontends/isl6405.c \
../drivers/media/dvb/frontends/isl6421.c \
../drivers/media/dvb/frontends/isl6423.c \
../drivers/media/dvb/frontends/itd1000.c \
../drivers/media/dvb/frontends/l64781.c \
../drivers/media/dvb/frontends/lgdt3304.c \
../drivers/media/dvb/frontends/lgdt3305.c \
../drivers/media/dvb/frontends/lgdt330x.c \
../drivers/media/dvb/frontends/lgs8gl5.c \
../drivers/media/dvb/frontends/lgs8gxx.c \
../drivers/media/dvb/frontends/lnbp21.c \
../drivers/media/dvb/frontends/mb86a16.c \
../drivers/media/dvb/frontends/mt312.c \
../drivers/media/dvb/frontends/mt352.c \
../drivers/media/dvb/frontends/nxt200x.c \
../drivers/media/dvb/frontends/nxt6000.c \
../drivers/media/dvb/frontends/or51132.c \
../drivers/media/dvb/frontends/or51211.c \
../drivers/media/dvb/frontends/s5h1409.c \
../drivers/media/dvb/frontends/s5h1411.c \
../drivers/media/dvb/frontends/s5h1420.c \
../drivers/media/dvb/frontends/s921_core.c \
../drivers/media/dvb/frontends/s921_module.c \
../drivers/media/dvb/frontends/si21xx.c \
../drivers/media/dvb/frontends/sp8870.c \
../drivers/media/dvb/frontends/sp887x.c \
../drivers/media/dvb/frontends/stb0899_algo.c \
../drivers/media/dvb/frontends/stb0899_drv.c \
../drivers/media/dvb/frontends/stb6000.c \
../drivers/media/dvb/frontends/stb6100.c \
../drivers/media/dvb/frontends/stv0288.c \
../drivers/media/dvb/frontends/stv0297.c \
../drivers/media/dvb/frontends/stv0299.c \
../drivers/media/dvb/frontends/stv0900_core.c \
../drivers/media/dvb/frontends/stv0900_sw.c \
../drivers/media/dvb/frontends/stv090x.c \
../drivers/media/dvb/frontends/stv6110.c \
../drivers/media/dvb/frontends/stv6110x.c \
../drivers/media/dvb/frontends/tda10021.c \
../drivers/media/dvb/frontends/tda10023.c \
../drivers/media/dvb/frontends/tda10048.c \
../drivers/media/dvb/frontends/tda1004x.c \
../drivers/media/dvb/frontends/tda10086.c \
../drivers/media/dvb/frontends/tda665x.c \
../drivers/media/dvb/frontends/tda8083.c \
../drivers/media/dvb/frontends/tda8261.c \
../drivers/media/dvb/frontends/tda826x.c \
../drivers/media/dvb/frontends/tua6100.c \
../drivers/media/dvb/frontends/ves1820.c \
../drivers/media/dvb/frontends/ves1x93.c \
../drivers/media/dvb/frontends/zl10036.c \
../drivers/media/dvb/frontends/zl10039.c \
../drivers/media/dvb/frontends/zl10353.c 

OBJS += \
./drivers/media/dvb/frontends/af9013.o \
./drivers/media/dvb/frontends/atbm8830.o \
./drivers/media/dvb/frontends/au8522_decoder.o \
./drivers/media/dvb/frontends/au8522_dig.o \
./drivers/media/dvb/frontends/bcm3510.o \
./drivers/media/dvb/frontends/cx22700.o \
./drivers/media/dvb/frontends/cx22702.o \
./drivers/media/dvb/frontends/cx24110.o \
./drivers/media/dvb/frontends/cx24113.o \
./drivers/media/dvb/frontends/cx24116.o \
./drivers/media/dvb/frontends/cx24123.o \
./drivers/media/dvb/frontends/dib0070.o \
./drivers/media/dvb/frontends/dib0090.o \
./drivers/media/dvb/frontends/dib3000mb.o \
./drivers/media/dvb/frontends/dib3000mc.o \
./drivers/media/dvb/frontends/dib7000m.o \
./drivers/media/dvb/frontends/dib7000p.o \
./drivers/media/dvb/frontends/dib8000.o \
./drivers/media/dvb/frontends/dibx000_common.o \
./drivers/media/dvb/frontends/drx397xD.o \
./drivers/media/dvb/frontends/ds3000.o \
./drivers/media/dvb/frontends/dvb-pll.o \
./drivers/media/dvb/frontends/dvb_dummy_fe.o \
./drivers/media/dvb/frontends/ec100.o \
./drivers/media/dvb/frontends/isl6405.o \
./drivers/media/dvb/frontends/isl6421.o \
./drivers/media/dvb/frontends/isl6423.o \
./drivers/media/dvb/frontends/itd1000.o \
./drivers/media/dvb/frontends/l64781.o \
./drivers/media/dvb/frontends/lgdt3304.o \
./drivers/media/dvb/frontends/lgdt3305.o \
./drivers/media/dvb/frontends/lgdt330x.o \
./drivers/media/dvb/frontends/lgs8gl5.o \
./drivers/media/dvb/frontends/lgs8gxx.o \
./drivers/media/dvb/frontends/lnbp21.o \
./drivers/media/dvb/frontends/mb86a16.o \
./drivers/media/dvb/frontends/mt312.o \
./drivers/media/dvb/frontends/mt352.o \
./drivers/media/dvb/frontends/nxt200x.o \
./drivers/media/dvb/frontends/nxt6000.o \
./drivers/media/dvb/frontends/or51132.o \
./drivers/media/dvb/frontends/or51211.o \
./drivers/media/dvb/frontends/s5h1409.o \
./drivers/media/dvb/frontends/s5h1411.o \
./drivers/media/dvb/frontends/s5h1420.o \
./drivers/media/dvb/frontends/s921_core.o \
./drivers/media/dvb/frontends/s921_module.o \
./drivers/media/dvb/frontends/si21xx.o \
./drivers/media/dvb/frontends/sp8870.o \
./drivers/media/dvb/frontends/sp887x.o \
./drivers/media/dvb/frontends/stb0899_algo.o \
./drivers/media/dvb/frontends/stb0899_drv.o \
./drivers/media/dvb/frontends/stb6000.o \
./drivers/media/dvb/frontends/stb6100.o \
./drivers/media/dvb/frontends/stv0288.o \
./drivers/media/dvb/frontends/stv0297.o \
./drivers/media/dvb/frontends/stv0299.o \
./drivers/media/dvb/frontends/stv0900_core.o \
./drivers/media/dvb/frontends/stv0900_sw.o \
./drivers/media/dvb/frontends/stv090x.o \
./drivers/media/dvb/frontends/stv6110.o \
./drivers/media/dvb/frontends/stv6110x.o \
./drivers/media/dvb/frontends/tda10021.o \
./drivers/media/dvb/frontends/tda10023.o \
./drivers/media/dvb/frontends/tda10048.o \
./drivers/media/dvb/frontends/tda1004x.o \
./drivers/media/dvb/frontends/tda10086.o \
./drivers/media/dvb/frontends/tda665x.o \
./drivers/media/dvb/frontends/tda8083.o \
./drivers/media/dvb/frontends/tda8261.o \
./drivers/media/dvb/frontends/tda826x.o \
./drivers/media/dvb/frontends/tua6100.o \
./drivers/media/dvb/frontends/ves1820.o \
./drivers/media/dvb/frontends/ves1x93.o \
./drivers/media/dvb/frontends/zl10036.o \
./drivers/media/dvb/frontends/zl10039.o \
./drivers/media/dvb/frontends/zl10353.o 

C_DEPS += \
./drivers/media/dvb/frontends/af9013.d \
./drivers/media/dvb/frontends/atbm8830.d \
./drivers/media/dvb/frontends/au8522_decoder.d \
./drivers/media/dvb/frontends/au8522_dig.d \
./drivers/media/dvb/frontends/bcm3510.d \
./drivers/media/dvb/frontends/cx22700.d \
./drivers/media/dvb/frontends/cx22702.d \
./drivers/media/dvb/frontends/cx24110.d \
./drivers/media/dvb/frontends/cx24113.d \
./drivers/media/dvb/frontends/cx24116.d \
./drivers/media/dvb/frontends/cx24123.d \
./drivers/media/dvb/frontends/dib0070.d \
./drivers/media/dvb/frontends/dib0090.d \
./drivers/media/dvb/frontends/dib3000mb.d \
./drivers/media/dvb/frontends/dib3000mc.d \
./drivers/media/dvb/frontends/dib7000m.d \
./drivers/media/dvb/frontends/dib7000p.d \
./drivers/media/dvb/frontends/dib8000.d \
./drivers/media/dvb/frontends/dibx000_common.d \
./drivers/media/dvb/frontends/drx397xD.d \
./drivers/media/dvb/frontends/ds3000.d \
./drivers/media/dvb/frontends/dvb-pll.d \
./drivers/media/dvb/frontends/dvb_dummy_fe.d \
./drivers/media/dvb/frontends/ec100.d \
./drivers/media/dvb/frontends/isl6405.d \
./drivers/media/dvb/frontends/isl6421.d \
./drivers/media/dvb/frontends/isl6423.d \
./drivers/media/dvb/frontends/itd1000.d \
./drivers/media/dvb/frontends/l64781.d \
./drivers/media/dvb/frontends/lgdt3304.d \
./drivers/media/dvb/frontends/lgdt3305.d \
./drivers/media/dvb/frontends/lgdt330x.d \
./drivers/media/dvb/frontends/lgs8gl5.d \
./drivers/media/dvb/frontends/lgs8gxx.d \
./drivers/media/dvb/frontends/lnbp21.d \
./drivers/media/dvb/frontends/mb86a16.d \
./drivers/media/dvb/frontends/mt312.d \
./drivers/media/dvb/frontends/mt352.d \
./drivers/media/dvb/frontends/nxt200x.d \
./drivers/media/dvb/frontends/nxt6000.d \
./drivers/media/dvb/frontends/or51132.d \
./drivers/media/dvb/frontends/or51211.d \
./drivers/media/dvb/frontends/s5h1409.d \
./drivers/media/dvb/frontends/s5h1411.d \
./drivers/media/dvb/frontends/s5h1420.d \
./drivers/media/dvb/frontends/s921_core.d \
./drivers/media/dvb/frontends/s921_module.d \
./drivers/media/dvb/frontends/si21xx.d \
./drivers/media/dvb/frontends/sp8870.d \
./drivers/media/dvb/frontends/sp887x.d \
./drivers/media/dvb/frontends/stb0899_algo.d \
./drivers/media/dvb/frontends/stb0899_drv.d \
./drivers/media/dvb/frontends/stb6000.d \
./drivers/media/dvb/frontends/stb6100.d \
./drivers/media/dvb/frontends/stv0288.d \
./drivers/media/dvb/frontends/stv0297.d \
./drivers/media/dvb/frontends/stv0299.d \
./drivers/media/dvb/frontends/stv0900_core.d \
./drivers/media/dvb/frontends/stv0900_sw.d \
./drivers/media/dvb/frontends/stv090x.d \
./drivers/media/dvb/frontends/stv6110.d \
./drivers/media/dvb/frontends/stv6110x.d \
./drivers/media/dvb/frontends/tda10021.d \
./drivers/media/dvb/frontends/tda10023.d \
./drivers/media/dvb/frontends/tda10048.d \
./drivers/media/dvb/frontends/tda1004x.d \
./drivers/media/dvb/frontends/tda10086.d \
./drivers/media/dvb/frontends/tda665x.d \
./drivers/media/dvb/frontends/tda8083.d \
./drivers/media/dvb/frontends/tda8261.d \
./drivers/media/dvb/frontends/tda826x.d \
./drivers/media/dvb/frontends/tua6100.d \
./drivers/media/dvb/frontends/ves1820.d \
./drivers/media/dvb/frontends/ves1x93.d \
./drivers/media/dvb/frontends/zl10036.d \
./drivers/media/dvb/frontends/zl10039.d \
./drivers/media/dvb/frontends/zl10353.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/media/dvb/frontends/%.o: ../drivers/media/dvb/frontends/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


