################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/watchdog/acquirewdt.c \
../drivers/watchdog/advantechwdt.c \
../drivers/watchdog/adx_wdt.c \
../drivers/watchdog/alim1535_wdt.c \
../drivers/watchdog/alim7101_wdt.c \
../drivers/watchdog/ar7_wdt.c \
../drivers/watchdog/at32ap700x_wdt.c \
../drivers/watchdog/at91rm9200_wdt.c \
../drivers/watchdog/at91sam9_wdt.c \
../drivers/watchdog/bcm47xx_wdt.c \
../drivers/watchdog/bfin_wdt.c \
../drivers/watchdog/booke_wdt.c \
../drivers/watchdog/coh901327_wdt.c \
../drivers/watchdog/cpu5wdt.c \
../drivers/watchdog/cpwd.c \
../drivers/watchdog/davinci_wdt.c \
../drivers/watchdog/ep93xx_wdt.c \
../drivers/watchdog/eurotechwdt.c \
../drivers/watchdog/gef_wdt.c \
../drivers/watchdog/geodewdt.c \
../drivers/watchdog/hpwdt.c \
../drivers/watchdog/i6300esb.c \
../drivers/watchdog/iTCO_vendor_support.c \
../drivers/watchdog/iTCO_wdt.c \
../drivers/watchdog/ib700wdt.c \
../drivers/watchdog/ibmasr.c \
../drivers/watchdog/indydog.c \
../drivers/watchdog/iop_wdt.c \
../drivers/watchdog/it8712f_wdt.c \
../drivers/watchdog/it87_wdt.c \
../drivers/watchdog/ixp2000_wdt.c \
../drivers/watchdog/ixp4xx_wdt.c \
../drivers/watchdog/ks8695_wdt.c \
../drivers/watchdog/machzwd.c \
../drivers/watchdog/max63xx_wdt.c \
../drivers/watchdog/mixcomwd.c \
../drivers/watchdog/mpc8xxx_wdt.c \
../drivers/watchdog/mpcore_wdt.c \
../drivers/watchdog/mtx-1_wdt.c \
../drivers/watchdog/mv64x60_wdt.c \
../drivers/watchdog/nuc900_wdt.c \
../drivers/watchdog/omap_wdt.c \
../drivers/watchdog/orion_wdt.c \
../drivers/watchdog/pc87413_wdt.c \
../drivers/watchdog/pcwd.c \
../drivers/watchdog/pcwd_pci.c \
../drivers/watchdog/pcwd_usb.c \
../drivers/watchdog/pika_wdt.c \
../drivers/watchdog/pnx4008_wdt.c \
../drivers/watchdog/pnx833x_wdt.c \
../drivers/watchdog/rc32434_wdt.c \
../drivers/watchdog/rdc321x_wdt.c \
../drivers/watchdog/riowd.c \
../drivers/watchdog/s3c2410_wdt.c \
../drivers/watchdog/sa1100_wdt.c \
../drivers/watchdog/sb_wdog.c \
../drivers/watchdog/sbc60xxwdt.c \
../drivers/watchdog/sbc7240_wdt.c \
../drivers/watchdog/sbc8360.c \
../drivers/watchdog/sbc_epx_c3.c \
../drivers/watchdog/sbc_fitpc2_wdt.c \
../drivers/watchdog/sc1200wdt.c \
../drivers/watchdog/sc520_wdt.c \
../drivers/watchdog/sch311x_wdt.c \
../drivers/watchdog/scx200_wdt.c \
../drivers/watchdog/shwdt.c \
../drivers/watchdog/smsc37b787_wdt.c \
../drivers/watchdog/softdog.c \
../drivers/watchdog/stmp3xxx_wdt.c \
../drivers/watchdog/ts72xx_wdt.c \
../drivers/watchdog/twl4030_wdt.c \
../drivers/watchdog/txx9wdt.c \
../drivers/watchdog/w83627hf_wdt.c \
../drivers/watchdog/w83697hf_wdt.c \
../drivers/watchdog/w83697ug_wdt.c \
../drivers/watchdog/w83877f_wdt.c \
../drivers/watchdog/w83977f_wdt.c \
../drivers/watchdog/wafer5823wdt.c \
../drivers/watchdog/wdrtas.c \
../drivers/watchdog/wdt.c \
../drivers/watchdog/wdt285.c \
../drivers/watchdog/wdt977.c \
../drivers/watchdog/wdt_pci.c \
../drivers/watchdog/wm831x_wdt.c \
../drivers/watchdog/wm8350_wdt.c 

OBJS += \
./drivers/watchdog/acquirewdt.o \
./drivers/watchdog/advantechwdt.o \
./drivers/watchdog/adx_wdt.o \
./drivers/watchdog/alim1535_wdt.o \
./drivers/watchdog/alim7101_wdt.o \
./drivers/watchdog/ar7_wdt.o \
./drivers/watchdog/at32ap700x_wdt.o \
./drivers/watchdog/at91rm9200_wdt.o \
./drivers/watchdog/at91sam9_wdt.o \
./drivers/watchdog/bcm47xx_wdt.o \
./drivers/watchdog/bfin_wdt.o \
./drivers/watchdog/booke_wdt.o \
./drivers/watchdog/coh901327_wdt.o \
./drivers/watchdog/cpu5wdt.o \
./drivers/watchdog/cpwd.o \
./drivers/watchdog/davinci_wdt.o \
./drivers/watchdog/ep93xx_wdt.o \
./drivers/watchdog/eurotechwdt.o \
./drivers/watchdog/gef_wdt.o \
./drivers/watchdog/geodewdt.o \
./drivers/watchdog/hpwdt.o \
./drivers/watchdog/i6300esb.o \
./drivers/watchdog/iTCO_vendor_support.o \
./drivers/watchdog/iTCO_wdt.o \
./drivers/watchdog/ib700wdt.o \
./drivers/watchdog/ibmasr.o \
./drivers/watchdog/indydog.o \
./drivers/watchdog/iop_wdt.o \
./drivers/watchdog/it8712f_wdt.o \
./drivers/watchdog/it87_wdt.o \
./drivers/watchdog/ixp2000_wdt.o \
./drivers/watchdog/ixp4xx_wdt.o \
./drivers/watchdog/ks8695_wdt.o \
./drivers/watchdog/machzwd.o \
./drivers/watchdog/max63xx_wdt.o \
./drivers/watchdog/mixcomwd.o \
./drivers/watchdog/mpc8xxx_wdt.o \
./drivers/watchdog/mpcore_wdt.o \
./drivers/watchdog/mtx-1_wdt.o \
./drivers/watchdog/mv64x60_wdt.o \
./drivers/watchdog/nuc900_wdt.o \
./drivers/watchdog/omap_wdt.o \
./drivers/watchdog/orion_wdt.o \
./drivers/watchdog/pc87413_wdt.o \
./drivers/watchdog/pcwd.o \
./drivers/watchdog/pcwd_pci.o \
./drivers/watchdog/pcwd_usb.o \
./drivers/watchdog/pika_wdt.o \
./drivers/watchdog/pnx4008_wdt.o \
./drivers/watchdog/pnx833x_wdt.o \
./drivers/watchdog/rc32434_wdt.o \
./drivers/watchdog/rdc321x_wdt.o \
./drivers/watchdog/riowd.o \
./drivers/watchdog/s3c2410_wdt.o \
./drivers/watchdog/sa1100_wdt.o \
./drivers/watchdog/sb_wdog.o \
./drivers/watchdog/sbc60xxwdt.o \
./drivers/watchdog/sbc7240_wdt.o \
./drivers/watchdog/sbc8360.o \
./drivers/watchdog/sbc_epx_c3.o \
./drivers/watchdog/sbc_fitpc2_wdt.o \
./drivers/watchdog/sc1200wdt.o \
./drivers/watchdog/sc520_wdt.o \
./drivers/watchdog/sch311x_wdt.o \
./drivers/watchdog/scx200_wdt.o \
./drivers/watchdog/shwdt.o \
./drivers/watchdog/smsc37b787_wdt.o \
./drivers/watchdog/softdog.o \
./drivers/watchdog/stmp3xxx_wdt.o \
./drivers/watchdog/ts72xx_wdt.o \
./drivers/watchdog/twl4030_wdt.o \
./drivers/watchdog/txx9wdt.o \
./drivers/watchdog/w83627hf_wdt.o \
./drivers/watchdog/w83697hf_wdt.o \
./drivers/watchdog/w83697ug_wdt.o \
./drivers/watchdog/w83877f_wdt.o \
./drivers/watchdog/w83977f_wdt.o \
./drivers/watchdog/wafer5823wdt.o \
./drivers/watchdog/wdrtas.o \
./drivers/watchdog/wdt.o \
./drivers/watchdog/wdt285.o \
./drivers/watchdog/wdt977.o \
./drivers/watchdog/wdt_pci.o \
./drivers/watchdog/wm831x_wdt.o \
./drivers/watchdog/wm8350_wdt.o 

C_DEPS += \
./drivers/watchdog/acquirewdt.d \
./drivers/watchdog/advantechwdt.d \
./drivers/watchdog/adx_wdt.d \
./drivers/watchdog/alim1535_wdt.d \
./drivers/watchdog/alim7101_wdt.d \
./drivers/watchdog/ar7_wdt.d \
./drivers/watchdog/at32ap700x_wdt.d \
./drivers/watchdog/at91rm9200_wdt.d \
./drivers/watchdog/at91sam9_wdt.d \
./drivers/watchdog/bcm47xx_wdt.d \
./drivers/watchdog/bfin_wdt.d \
./drivers/watchdog/booke_wdt.d \
./drivers/watchdog/coh901327_wdt.d \
./drivers/watchdog/cpu5wdt.d \
./drivers/watchdog/cpwd.d \
./drivers/watchdog/davinci_wdt.d \
./drivers/watchdog/ep93xx_wdt.d \
./drivers/watchdog/eurotechwdt.d \
./drivers/watchdog/gef_wdt.d \
./drivers/watchdog/geodewdt.d \
./drivers/watchdog/hpwdt.d \
./drivers/watchdog/i6300esb.d \
./drivers/watchdog/iTCO_vendor_support.d \
./drivers/watchdog/iTCO_wdt.d \
./drivers/watchdog/ib700wdt.d \
./drivers/watchdog/ibmasr.d \
./drivers/watchdog/indydog.d \
./drivers/watchdog/iop_wdt.d \
./drivers/watchdog/it8712f_wdt.d \
./drivers/watchdog/it87_wdt.d \
./drivers/watchdog/ixp2000_wdt.d \
./drivers/watchdog/ixp4xx_wdt.d \
./drivers/watchdog/ks8695_wdt.d \
./drivers/watchdog/machzwd.d \
./drivers/watchdog/max63xx_wdt.d \
./drivers/watchdog/mixcomwd.d \
./drivers/watchdog/mpc8xxx_wdt.d \
./drivers/watchdog/mpcore_wdt.d \
./drivers/watchdog/mtx-1_wdt.d \
./drivers/watchdog/mv64x60_wdt.d \
./drivers/watchdog/nuc900_wdt.d \
./drivers/watchdog/omap_wdt.d \
./drivers/watchdog/orion_wdt.d \
./drivers/watchdog/pc87413_wdt.d \
./drivers/watchdog/pcwd.d \
./drivers/watchdog/pcwd_pci.d \
./drivers/watchdog/pcwd_usb.d \
./drivers/watchdog/pika_wdt.d \
./drivers/watchdog/pnx4008_wdt.d \
./drivers/watchdog/pnx833x_wdt.d \
./drivers/watchdog/rc32434_wdt.d \
./drivers/watchdog/rdc321x_wdt.d \
./drivers/watchdog/riowd.d \
./drivers/watchdog/s3c2410_wdt.d \
./drivers/watchdog/sa1100_wdt.d \
./drivers/watchdog/sb_wdog.d \
./drivers/watchdog/sbc60xxwdt.d \
./drivers/watchdog/sbc7240_wdt.d \
./drivers/watchdog/sbc8360.d \
./drivers/watchdog/sbc_epx_c3.d \
./drivers/watchdog/sbc_fitpc2_wdt.d \
./drivers/watchdog/sc1200wdt.d \
./drivers/watchdog/sc520_wdt.d \
./drivers/watchdog/sch311x_wdt.d \
./drivers/watchdog/scx200_wdt.d \
./drivers/watchdog/shwdt.d \
./drivers/watchdog/smsc37b787_wdt.d \
./drivers/watchdog/softdog.d \
./drivers/watchdog/stmp3xxx_wdt.d \
./drivers/watchdog/ts72xx_wdt.d \
./drivers/watchdog/twl4030_wdt.d \
./drivers/watchdog/txx9wdt.d \
./drivers/watchdog/w83627hf_wdt.d \
./drivers/watchdog/w83697hf_wdt.d \
./drivers/watchdog/w83697ug_wdt.d \
./drivers/watchdog/w83877f_wdt.d \
./drivers/watchdog/w83977f_wdt.d \
./drivers/watchdog/wafer5823wdt.d \
./drivers/watchdog/wdrtas.d \
./drivers/watchdog/wdt.d \
./drivers/watchdog/wdt285.d \
./drivers/watchdog/wdt977.d \
./drivers/watchdog/wdt_pci.d \
./drivers/watchdog/wm831x_wdt.d \
./drivers/watchdog/wm8350_wdt.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/watchdog/%.o: ../drivers/watchdog/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


