################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/acpi/acpica/acpi.o \
../drivers/acpi/acpica/built-in.o \
../drivers/acpi/acpica/dsfield.o \
../drivers/acpi/acpica/dsinit.o \
../drivers/acpi/acpica/dsmethod.o \
../drivers/acpi/acpica/dsmthdat.o \
../drivers/acpi/acpica/dsobject.o \
../drivers/acpi/acpica/dsopcode.o \
../drivers/acpi/acpica/dsutils.o \
../drivers/acpi/acpica/dswexec.o \
../drivers/acpi/acpica/dswload.o \
../drivers/acpi/acpica/dswscope.o \
../drivers/acpi/acpica/dswstate.o \
../drivers/acpi/acpica/evevent.o \
../drivers/acpi/acpica/evgpe.o \
../drivers/acpi/acpica/evgpeblk.o \
../drivers/acpi/acpica/evmisc.o \
../drivers/acpi/acpica/evregion.o \
../drivers/acpi/acpica/evrgnini.o \
../drivers/acpi/acpica/evsci.o \
../drivers/acpi/acpica/evxface.o \
../drivers/acpi/acpica/evxfevnt.o \
../drivers/acpi/acpica/evxfregn.o \
../drivers/acpi/acpica/exconfig.o \
../drivers/acpi/acpica/exconvrt.o \
../drivers/acpi/acpica/excreate.o \
../drivers/acpi/acpica/exdump.o \
../drivers/acpi/acpica/exfield.o \
../drivers/acpi/acpica/exfldio.o \
../drivers/acpi/acpica/exmisc.o \
../drivers/acpi/acpica/exmutex.o \
../drivers/acpi/acpica/exnames.o \
../drivers/acpi/acpica/exoparg1.o \
../drivers/acpi/acpica/exoparg2.o \
../drivers/acpi/acpica/exoparg3.o \
../drivers/acpi/acpica/exoparg6.o \
../drivers/acpi/acpica/exprep.o \
../drivers/acpi/acpica/exregion.o \
../drivers/acpi/acpica/exresnte.o \
../drivers/acpi/acpica/exresolv.o \
../drivers/acpi/acpica/exresop.o \
../drivers/acpi/acpica/exstore.o \
../drivers/acpi/acpica/exstoren.o \
../drivers/acpi/acpica/exstorob.o \
../drivers/acpi/acpica/exsystem.o \
../drivers/acpi/acpica/exutils.o \
../drivers/acpi/acpica/hwacpi.o \
../drivers/acpi/acpica/hwgpe.o \
../drivers/acpi/acpica/hwregs.o \
../drivers/acpi/acpica/hwsleep.o \
../drivers/acpi/acpica/hwvalid.o \
../drivers/acpi/acpica/hwxface.o \
../drivers/acpi/acpica/nsaccess.o \
../drivers/acpi/acpica/nsalloc.o \
../drivers/acpi/acpica/nsdump.o \
../drivers/acpi/acpica/nseval.o \
../drivers/acpi/acpica/nsinit.o \
../drivers/acpi/acpica/nsload.o \
../drivers/acpi/acpica/nsnames.o \
../drivers/acpi/acpica/nsobject.o \
../drivers/acpi/acpica/nsparse.o \
../drivers/acpi/acpica/nspredef.o \
../drivers/acpi/acpica/nsrepair.o \
../drivers/acpi/acpica/nsrepair2.o \
../drivers/acpi/acpica/nssearch.o \
../drivers/acpi/acpica/nsutils.o \
../drivers/acpi/acpica/nswalk.o \
../drivers/acpi/acpica/nsxfeval.o \
../drivers/acpi/acpica/nsxfname.o \
../drivers/acpi/acpica/nsxfobj.o \
../drivers/acpi/acpica/psargs.o \
../drivers/acpi/acpica/psloop.o \
../drivers/acpi/acpica/psopcode.o \
../drivers/acpi/acpica/psparse.o \
../drivers/acpi/acpica/psscope.o \
../drivers/acpi/acpica/pstree.o \
../drivers/acpi/acpica/psutils.o \
../drivers/acpi/acpica/pswalk.o \
../drivers/acpi/acpica/psxface.o \
../drivers/acpi/acpica/rsaddr.o \
../drivers/acpi/acpica/rscalc.o \
../drivers/acpi/acpica/rscreate.o \
../drivers/acpi/acpica/rsinfo.o \
../drivers/acpi/acpica/rsio.o \
../drivers/acpi/acpica/rsirq.o \
../drivers/acpi/acpica/rslist.o \
../drivers/acpi/acpica/rsmemory.o \
../drivers/acpi/acpica/rsmisc.o \
../drivers/acpi/acpica/rsutils.o \
../drivers/acpi/acpica/rsxface.o \
../drivers/acpi/acpica/tbfadt.o \
../drivers/acpi/acpica/tbfind.o \
../drivers/acpi/acpica/tbinstal.o \
../drivers/acpi/acpica/tbutils.o \
../drivers/acpi/acpica/tbxface.o \
../drivers/acpi/acpica/tbxfroot.o \
../drivers/acpi/acpica/utalloc.o \
../drivers/acpi/acpica/utcopy.o \
../drivers/acpi/acpica/utdebug.o \
../drivers/acpi/acpica/utdelete.o \
../drivers/acpi/acpica/uteval.o \
../drivers/acpi/acpica/utglobal.o \
../drivers/acpi/acpica/utids.o \
../drivers/acpi/acpica/utinit.o \
../drivers/acpi/acpica/utlock.o \
../drivers/acpi/acpica/utmath.o \
../drivers/acpi/acpica/utmisc.o \
../drivers/acpi/acpica/utmutex.o \
../drivers/acpi/acpica/utobject.o \
../drivers/acpi/acpica/utresrc.o \
../drivers/acpi/acpica/utstate.o \
../drivers/acpi/acpica/utxface.o 

C_SRCS += \
../drivers/acpi/acpica/dsfield.c \
../drivers/acpi/acpica/dsinit.c \
../drivers/acpi/acpica/dsmethod.c \
../drivers/acpi/acpica/dsmthdat.c \
../drivers/acpi/acpica/dsobject.c \
../drivers/acpi/acpica/dsopcode.c \
../drivers/acpi/acpica/dsutils.c \
../drivers/acpi/acpica/dswexec.c \
../drivers/acpi/acpica/dswload.c \
../drivers/acpi/acpica/dswscope.c \
../drivers/acpi/acpica/dswstate.c \
../drivers/acpi/acpica/evevent.c \
../drivers/acpi/acpica/evgpe.c \
../drivers/acpi/acpica/evgpeblk.c \
../drivers/acpi/acpica/evmisc.c \
../drivers/acpi/acpica/evregion.c \
../drivers/acpi/acpica/evrgnini.c \
../drivers/acpi/acpica/evsci.c \
../drivers/acpi/acpica/evxface.c \
../drivers/acpi/acpica/evxfevnt.c \
../drivers/acpi/acpica/evxfregn.c \
../drivers/acpi/acpica/exconfig.c \
../drivers/acpi/acpica/exconvrt.c \
../drivers/acpi/acpica/excreate.c \
../drivers/acpi/acpica/exdump.c \
../drivers/acpi/acpica/exfield.c \
../drivers/acpi/acpica/exfldio.c \
../drivers/acpi/acpica/exmisc.c \
../drivers/acpi/acpica/exmutex.c \
../drivers/acpi/acpica/exnames.c \
../drivers/acpi/acpica/exoparg1.c \
../drivers/acpi/acpica/exoparg2.c \
../drivers/acpi/acpica/exoparg3.c \
../drivers/acpi/acpica/exoparg6.c \
../drivers/acpi/acpica/exprep.c \
../drivers/acpi/acpica/exregion.c \
../drivers/acpi/acpica/exresnte.c \
../drivers/acpi/acpica/exresolv.c \
../drivers/acpi/acpica/exresop.c \
../drivers/acpi/acpica/exstore.c \
../drivers/acpi/acpica/exstoren.c \
../drivers/acpi/acpica/exstorob.c \
../drivers/acpi/acpica/exsystem.c \
../drivers/acpi/acpica/exutils.c \
../drivers/acpi/acpica/hwacpi.c \
../drivers/acpi/acpica/hwgpe.c \
../drivers/acpi/acpica/hwregs.c \
../drivers/acpi/acpica/hwsleep.c \
../drivers/acpi/acpica/hwtimer.c \
../drivers/acpi/acpica/hwvalid.c \
../drivers/acpi/acpica/hwxface.c \
../drivers/acpi/acpica/nsaccess.c \
../drivers/acpi/acpica/nsalloc.c \
../drivers/acpi/acpica/nsdump.c \
../drivers/acpi/acpica/nsdumpdv.c \
../drivers/acpi/acpica/nseval.c \
../drivers/acpi/acpica/nsinit.c \
../drivers/acpi/acpica/nsload.c \
../drivers/acpi/acpica/nsnames.c \
../drivers/acpi/acpica/nsobject.c \
../drivers/acpi/acpica/nsparse.c \
../drivers/acpi/acpica/nspredef.c \
../drivers/acpi/acpica/nsrepair.c \
../drivers/acpi/acpica/nsrepair2.c \
../drivers/acpi/acpica/nssearch.c \
../drivers/acpi/acpica/nsutils.c \
../drivers/acpi/acpica/nswalk.c \
../drivers/acpi/acpica/nsxfeval.c \
../drivers/acpi/acpica/nsxfname.c \
../drivers/acpi/acpica/nsxfobj.c \
../drivers/acpi/acpica/psargs.c \
../drivers/acpi/acpica/psloop.c \
../drivers/acpi/acpica/psopcode.c \
../drivers/acpi/acpica/psparse.c \
../drivers/acpi/acpica/psscope.c \
../drivers/acpi/acpica/pstree.c \
../drivers/acpi/acpica/psutils.c \
../drivers/acpi/acpica/pswalk.c \
../drivers/acpi/acpica/psxface.c \
../drivers/acpi/acpica/rsaddr.c \
../drivers/acpi/acpica/rscalc.c \
../drivers/acpi/acpica/rscreate.c \
../drivers/acpi/acpica/rsdump.c \
../drivers/acpi/acpica/rsinfo.c \
../drivers/acpi/acpica/rsio.c \
../drivers/acpi/acpica/rsirq.c \
../drivers/acpi/acpica/rslist.c \
../drivers/acpi/acpica/rsmemory.c \
../drivers/acpi/acpica/rsmisc.c \
../drivers/acpi/acpica/rsutils.c \
../drivers/acpi/acpica/rsxface.c \
../drivers/acpi/acpica/tbfadt.c \
../drivers/acpi/acpica/tbfind.c \
../drivers/acpi/acpica/tbinstal.c \
../drivers/acpi/acpica/tbutils.c \
../drivers/acpi/acpica/tbxface.c \
../drivers/acpi/acpica/tbxfroot.c \
../drivers/acpi/acpica/utalloc.c \
../drivers/acpi/acpica/utcopy.c \
../drivers/acpi/acpica/utdebug.c \
../drivers/acpi/acpica/utdelete.c \
../drivers/acpi/acpica/uteval.c \
../drivers/acpi/acpica/utglobal.c \
../drivers/acpi/acpica/utids.c \
../drivers/acpi/acpica/utinit.c \
../drivers/acpi/acpica/utlock.c \
../drivers/acpi/acpica/utmath.c \
../drivers/acpi/acpica/utmisc.c \
../drivers/acpi/acpica/utmutex.c \
../drivers/acpi/acpica/utobject.c \
../drivers/acpi/acpica/utresrc.c \
../drivers/acpi/acpica/utstate.c \
../drivers/acpi/acpica/utxface.c 

OBJS += \
./drivers/acpi/acpica/dsfield.o \
./drivers/acpi/acpica/dsinit.o \
./drivers/acpi/acpica/dsmethod.o \
./drivers/acpi/acpica/dsmthdat.o \
./drivers/acpi/acpica/dsobject.o \
./drivers/acpi/acpica/dsopcode.o \
./drivers/acpi/acpica/dsutils.o \
./drivers/acpi/acpica/dswexec.o \
./drivers/acpi/acpica/dswload.o \
./drivers/acpi/acpica/dswscope.o \
./drivers/acpi/acpica/dswstate.o \
./drivers/acpi/acpica/evevent.o \
./drivers/acpi/acpica/evgpe.o \
./drivers/acpi/acpica/evgpeblk.o \
./drivers/acpi/acpica/evmisc.o \
./drivers/acpi/acpica/evregion.o \
./drivers/acpi/acpica/evrgnini.o \
./drivers/acpi/acpica/evsci.o \
./drivers/acpi/acpica/evxface.o \
./drivers/acpi/acpica/evxfevnt.o \
./drivers/acpi/acpica/evxfregn.o \
./drivers/acpi/acpica/exconfig.o \
./drivers/acpi/acpica/exconvrt.o \
./drivers/acpi/acpica/excreate.o \
./drivers/acpi/acpica/exdump.o \
./drivers/acpi/acpica/exfield.o \
./drivers/acpi/acpica/exfldio.o \
./drivers/acpi/acpica/exmisc.o \
./drivers/acpi/acpica/exmutex.o \
./drivers/acpi/acpica/exnames.o \
./drivers/acpi/acpica/exoparg1.o \
./drivers/acpi/acpica/exoparg2.o \
./drivers/acpi/acpica/exoparg3.o \
./drivers/acpi/acpica/exoparg6.o \
./drivers/acpi/acpica/exprep.o \
./drivers/acpi/acpica/exregion.o \
./drivers/acpi/acpica/exresnte.o \
./drivers/acpi/acpica/exresolv.o \
./drivers/acpi/acpica/exresop.o \
./drivers/acpi/acpica/exstore.o \
./drivers/acpi/acpica/exstoren.o \
./drivers/acpi/acpica/exstorob.o \
./drivers/acpi/acpica/exsystem.o \
./drivers/acpi/acpica/exutils.o \
./drivers/acpi/acpica/hwacpi.o \
./drivers/acpi/acpica/hwgpe.o \
./drivers/acpi/acpica/hwregs.o \
./drivers/acpi/acpica/hwsleep.o \
./drivers/acpi/acpica/hwtimer.o \
./drivers/acpi/acpica/hwvalid.o \
./drivers/acpi/acpica/hwxface.o \
./drivers/acpi/acpica/nsaccess.o \
./drivers/acpi/acpica/nsalloc.o \
./drivers/acpi/acpica/nsdump.o \
./drivers/acpi/acpica/nsdumpdv.o \
./drivers/acpi/acpica/nseval.o \
./drivers/acpi/acpica/nsinit.o \
./drivers/acpi/acpica/nsload.o \
./drivers/acpi/acpica/nsnames.o \
./drivers/acpi/acpica/nsobject.o \
./drivers/acpi/acpica/nsparse.o \
./drivers/acpi/acpica/nspredef.o \
./drivers/acpi/acpica/nsrepair.o \
./drivers/acpi/acpica/nsrepair2.o \
./drivers/acpi/acpica/nssearch.o \
./drivers/acpi/acpica/nsutils.o \
./drivers/acpi/acpica/nswalk.o \
./drivers/acpi/acpica/nsxfeval.o \
./drivers/acpi/acpica/nsxfname.o \
./drivers/acpi/acpica/nsxfobj.o \
./drivers/acpi/acpica/psargs.o \
./drivers/acpi/acpica/psloop.o \
./drivers/acpi/acpica/psopcode.o \
./drivers/acpi/acpica/psparse.o \
./drivers/acpi/acpica/psscope.o \
./drivers/acpi/acpica/pstree.o \
./drivers/acpi/acpica/psutils.o \
./drivers/acpi/acpica/pswalk.o \
./drivers/acpi/acpica/psxface.o \
./drivers/acpi/acpica/rsaddr.o \
./drivers/acpi/acpica/rscalc.o \
./drivers/acpi/acpica/rscreate.o \
./drivers/acpi/acpica/rsdump.o \
./drivers/acpi/acpica/rsinfo.o \
./drivers/acpi/acpica/rsio.o \
./drivers/acpi/acpica/rsirq.o \
./drivers/acpi/acpica/rslist.o \
./drivers/acpi/acpica/rsmemory.o \
./drivers/acpi/acpica/rsmisc.o \
./drivers/acpi/acpica/rsutils.o \
./drivers/acpi/acpica/rsxface.o \
./drivers/acpi/acpica/tbfadt.o \
./drivers/acpi/acpica/tbfind.o \
./drivers/acpi/acpica/tbinstal.o \
./drivers/acpi/acpica/tbutils.o \
./drivers/acpi/acpica/tbxface.o \
./drivers/acpi/acpica/tbxfroot.o \
./drivers/acpi/acpica/utalloc.o \
./drivers/acpi/acpica/utcopy.o \
./drivers/acpi/acpica/utdebug.o \
./drivers/acpi/acpica/utdelete.o \
./drivers/acpi/acpica/uteval.o \
./drivers/acpi/acpica/utglobal.o \
./drivers/acpi/acpica/utids.o \
./drivers/acpi/acpica/utinit.o \
./drivers/acpi/acpica/utlock.o \
./drivers/acpi/acpica/utmath.o \
./drivers/acpi/acpica/utmisc.o \
./drivers/acpi/acpica/utmutex.o \
./drivers/acpi/acpica/utobject.o \
./drivers/acpi/acpica/utresrc.o \
./drivers/acpi/acpica/utstate.o \
./drivers/acpi/acpica/utxface.o 

C_DEPS += \
./drivers/acpi/acpica/dsfield.d \
./drivers/acpi/acpica/dsinit.d \
./drivers/acpi/acpica/dsmethod.d \
./drivers/acpi/acpica/dsmthdat.d \
./drivers/acpi/acpica/dsobject.d \
./drivers/acpi/acpica/dsopcode.d \
./drivers/acpi/acpica/dsutils.d \
./drivers/acpi/acpica/dswexec.d \
./drivers/acpi/acpica/dswload.d \
./drivers/acpi/acpica/dswscope.d \
./drivers/acpi/acpica/dswstate.d \
./drivers/acpi/acpica/evevent.d \
./drivers/acpi/acpica/evgpe.d \
./drivers/acpi/acpica/evgpeblk.d \
./drivers/acpi/acpica/evmisc.d \
./drivers/acpi/acpica/evregion.d \
./drivers/acpi/acpica/evrgnini.d \
./drivers/acpi/acpica/evsci.d \
./drivers/acpi/acpica/evxface.d \
./drivers/acpi/acpica/evxfevnt.d \
./drivers/acpi/acpica/evxfregn.d \
./drivers/acpi/acpica/exconfig.d \
./drivers/acpi/acpica/exconvrt.d \
./drivers/acpi/acpica/excreate.d \
./drivers/acpi/acpica/exdump.d \
./drivers/acpi/acpica/exfield.d \
./drivers/acpi/acpica/exfldio.d \
./drivers/acpi/acpica/exmisc.d \
./drivers/acpi/acpica/exmutex.d \
./drivers/acpi/acpica/exnames.d \
./drivers/acpi/acpica/exoparg1.d \
./drivers/acpi/acpica/exoparg2.d \
./drivers/acpi/acpica/exoparg3.d \
./drivers/acpi/acpica/exoparg6.d \
./drivers/acpi/acpica/exprep.d \
./drivers/acpi/acpica/exregion.d \
./drivers/acpi/acpica/exresnte.d \
./drivers/acpi/acpica/exresolv.d \
./drivers/acpi/acpica/exresop.d \
./drivers/acpi/acpica/exstore.d \
./drivers/acpi/acpica/exstoren.d \
./drivers/acpi/acpica/exstorob.d \
./drivers/acpi/acpica/exsystem.d \
./drivers/acpi/acpica/exutils.d \
./drivers/acpi/acpica/hwacpi.d \
./drivers/acpi/acpica/hwgpe.d \
./drivers/acpi/acpica/hwregs.d \
./drivers/acpi/acpica/hwsleep.d \
./drivers/acpi/acpica/hwtimer.d \
./drivers/acpi/acpica/hwvalid.d \
./drivers/acpi/acpica/hwxface.d \
./drivers/acpi/acpica/nsaccess.d \
./drivers/acpi/acpica/nsalloc.d \
./drivers/acpi/acpica/nsdump.d \
./drivers/acpi/acpica/nsdumpdv.d \
./drivers/acpi/acpica/nseval.d \
./drivers/acpi/acpica/nsinit.d \
./drivers/acpi/acpica/nsload.d \
./drivers/acpi/acpica/nsnames.d \
./drivers/acpi/acpica/nsobject.d \
./drivers/acpi/acpica/nsparse.d \
./drivers/acpi/acpica/nspredef.d \
./drivers/acpi/acpica/nsrepair.d \
./drivers/acpi/acpica/nsrepair2.d \
./drivers/acpi/acpica/nssearch.d \
./drivers/acpi/acpica/nsutils.d \
./drivers/acpi/acpica/nswalk.d \
./drivers/acpi/acpica/nsxfeval.d \
./drivers/acpi/acpica/nsxfname.d \
./drivers/acpi/acpica/nsxfobj.d \
./drivers/acpi/acpica/psargs.d \
./drivers/acpi/acpica/psloop.d \
./drivers/acpi/acpica/psopcode.d \
./drivers/acpi/acpica/psparse.d \
./drivers/acpi/acpica/psscope.d \
./drivers/acpi/acpica/pstree.d \
./drivers/acpi/acpica/psutils.d \
./drivers/acpi/acpica/pswalk.d \
./drivers/acpi/acpica/psxface.d \
./drivers/acpi/acpica/rsaddr.d \
./drivers/acpi/acpica/rscalc.d \
./drivers/acpi/acpica/rscreate.d \
./drivers/acpi/acpica/rsdump.d \
./drivers/acpi/acpica/rsinfo.d \
./drivers/acpi/acpica/rsio.d \
./drivers/acpi/acpica/rsirq.d \
./drivers/acpi/acpica/rslist.d \
./drivers/acpi/acpica/rsmemory.d \
./drivers/acpi/acpica/rsmisc.d \
./drivers/acpi/acpica/rsutils.d \
./drivers/acpi/acpica/rsxface.d \
./drivers/acpi/acpica/tbfadt.d \
./drivers/acpi/acpica/tbfind.d \
./drivers/acpi/acpica/tbinstal.d \
./drivers/acpi/acpica/tbutils.d \
./drivers/acpi/acpica/tbxface.d \
./drivers/acpi/acpica/tbxfroot.d \
./drivers/acpi/acpica/utalloc.d \
./drivers/acpi/acpica/utcopy.d \
./drivers/acpi/acpica/utdebug.d \
./drivers/acpi/acpica/utdelete.d \
./drivers/acpi/acpica/uteval.d \
./drivers/acpi/acpica/utglobal.d \
./drivers/acpi/acpica/utids.d \
./drivers/acpi/acpica/utinit.d \
./drivers/acpi/acpica/utlock.d \
./drivers/acpi/acpica/utmath.d \
./drivers/acpi/acpica/utmisc.d \
./drivers/acpi/acpica/utmutex.d \
./drivers/acpi/acpica/utobject.d \
./drivers/acpi/acpica/utresrc.d \
./drivers/acpi/acpica/utstate.d \
./drivers/acpi/acpica/utxface.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/acpi/acpica/%.o: ../drivers/acpi/acpica/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


