################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/staging/comedi/drivers/8255.c \
../drivers/staging/comedi/drivers/acl7225b.c \
../drivers/staging/comedi/drivers/addi_apci_035.c \
../drivers/staging/comedi/drivers/addi_apci_1032.c \
../drivers/staging/comedi/drivers/addi_apci_1500.c \
../drivers/staging/comedi/drivers/addi_apci_1516.c \
../drivers/staging/comedi/drivers/addi_apci_1564.c \
../drivers/staging/comedi/drivers/addi_apci_16xx.c \
../drivers/staging/comedi/drivers/addi_apci_1710.c \
../drivers/staging/comedi/drivers/addi_apci_2016.c \
../drivers/staging/comedi/drivers/addi_apci_2032.c \
../drivers/staging/comedi/drivers/addi_apci_2200.c \
../drivers/staging/comedi/drivers/addi_apci_3001.c \
../drivers/staging/comedi/drivers/addi_apci_3120.c \
../drivers/staging/comedi/drivers/addi_apci_3200.c \
../drivers/staging/comedi/drivers/addi_apci_3300.c \
../drivers/staging/comedi/drivers/addi_apci_3501.c \
../drivers/staging/comedi/drivers/addi_apci_3xxx.c \
../drivers/staging/comedi/drivers/addi_apci_all.c \
../drivers/staging/comedi/drivers/adl_pci6208.c \
../drivers/staging/comedi/drivers/adl_pci7296.c \
../drivers/staging/comedi/drivers/adl_pci7432.c \
../drivers/staging/comedi/drivers/adl_pci8164.c \
../drivers/staging/comedi/drivers/adl_pci9111.c \
../drivers/staging/comedi/drivers/adl_pci9118.c \
../drivers/staging/comedi/drivers/adq12b.c \
../drivers/staging/comedi/drivers/adv_pci1710.c \
../drivers/staging/comedi/drivers/adv_pci1723.c \
../drivers/staging/comedi/drivers/adv_pci_dio.c \
../drivers/staging/comedi/drivers/aio_aio12_8.c \
../drivers/staging/comedi/drivers/aio_iiro_16.c \
../drivers/staging/comedi/drivers/amplc_dio200.c \
../drivers/staging/comedi/drivers/amplc_pc236.c \
../drivers/staging/comedi/drivers/amplc_pc263.c \
../drivers/staging/comedi/drivers/amplc_pci224.c \
../drivers/staging/comedi/drivers/amplc_pci230.c \
../drivers/staging/comedi/drivers/c6xdigio.c \
../drivers/staging/comedi/drivers/cb_das16_cs.c \
../drivers/staging/comedi/drivers/cb_pcidas.c \
../drivers/staging/comedi/drivers/cb_pcidas64.c \
../drivers/staging/comedi/drivers/cb_pcidda.c \
../drivers/staging/comedi/drivers/cb_pcidio.c \
../drivers/staging/comedi/drivers/cb_pcimdas.c \
../drivers/staging/comedi/drivers/cb_pcimdda.c \
../drivers/staging/comedi/drivers/comedi_bond.c \
../drivers/staging/comedi/drivers/comedi_fc.c \
../drivers/staging/comedi/drivers/comedi_parport.c \
../drivers/staging/comedi/drivers/comedi_test.c \
../drivers/staging/comedi/drivers/contec_pci_dio.c \
../drivers/staging/comedi/drivers/daqboard2000.c \
../drivers/staging/comedi/drivers/das08.c \
../drivers/staging/comedi/drivers/das08_cs.c \
../drivers/staging/comedi/drivers/das16.c \
../drivers/staging/comedi/drivers/das16m1.c \
../drivers/staging/comedi/drivers/das1800.c \
../drivers/staging/comedi/drivers/das6402.c \
../drivers/staging/comedi/drivers/das800.c \
../drivers/staging/comedi/drivers/dmm32at.c \
../drivers/staging/comedi/drivers/dt2801.c \
../drivers/staging/comedi/drivers/dt2811.c \
../drivers/staging/comedi/drivers/dt2814.c \
../drivers/staging/comedi/drivers/dt2815.c \
../drivers/staging/comedi/drivers/dt2817.c \
../drivers/staging/comedi/drivers/dt282x.c \
../drivers/staging/comedi/drivers/dt3000.c \
../drivers/staging/comedi/drivers/dt9812.c \
../drivers/staging/comedi/drivers/fl512.c \
../drivers/staging/comedi/drivers/gsc_hpdi.c \
../drivers/staging/comedi/drivers/icp_multi.c \
../drivers/staging/comedi/drivers/ii_pci20kc.c \
../drivers/staging/comedi/drivers/jr3_pci.c \
../drivers/staging/comedi/drivers/ke_counter.c \
../drivers/staging/comedi/drivers/me4000.c \
../drivers/staging/comedi/drivers/me_daq.c \
../drivers/staging/comedi/drivers/mite.c \
../drivers/staging/comedi/drivers/mpc624.c \
../drivers/staging/comedi/drivers/mpc8260cpm.c \
../drivers/staging/comedi/drivers/multiq3.c \
../drivers/staging/comedi/drivers/ni_6527.c \
../drivers/staging/comedi/drivers/ni_65xx.c \
../drivers/staging/comedi/drivers/ni_660x.c \
../drivers/staging/comedi/drivers/ni_670x.c \
../drivers/staging/comedi/drivers/ni_at_a2150.c \
../drivers/staging/comedi/drivers/ni_at_ao.c \
../drivers/staging/comedi/drivers/ni_atmio.c \
../drivers/staging/comedi/drivers/ni_atmio16d.c \
../drivers/staging/comedi/drivers/ni_daq_700.c \
../drivers/staging/comedi/drivers/ni_daq_dio24.c \
../drivers/staging/comedi/drivers/ni_labpc.c \
../drivers/staging/comedi/drivers/ni_labpc_cs.c \
../drivers/staging/comedi/drivers/ni_mio_common.c \
../drivers/staging/comedi/drivers/ni_mio_cs.c \
../drivers/staging/comedi/drivers/ni_pcidio.c \
../drivers/staging/comedi/drivers/ni_pcimio.c \
../drivers/staging/comedi/drivers/ni_tio.c \
../drivers/staging/comedi/drivers/ni_tiocmd.c \
../drivers/staging/comedi/drivers/pcl711.c \
../drivers/staging/comedi/drivers/pcl724.c \
../drivers/staging/comedi/drivers/pcl725.c \
../drivers/staging/comedi/drivers/pcl726.c \
../drivers/staging/comedi/drivers/pcl730.c \
../drivers/staging/comedi/drivers/pcl812.c \
../drivers/staging/comedi/drivers/pcl816.c \
../drivers/staging/comedi/drivers/pcl818.c \
../drivers/staging/comedi/drivers/pcm3724.c \
../drivers/staging/comedi/drivers/pcm3730.c \
../drivers/staging/comedi/drivers/pcm_common.c \
../drivers/staging/comedi/drivers/pcmad.c \
../drivers/staging/comedi/drivers/pcmda12.c \
../drivers/staging/comedi/drivers/pcmmio.c \
../drivers/staging/comedi/drivers/pcmuio.c \
../drivers/staging/comedi/drivers/poc.c \
../drivers/staging/comedi/drivers/quatech_daqp_cs.c \
../drivers/staging/comedi/drivers/rtd520.c \
../drivers/staging/comedi/drivers/rti800.c \
../drivers/staging/comedi/drivers/rti802.c \
../drivers/staging/comedi/drivers/s526.c \
../drivers/staging/comedi/drivers/s626.c \
../drivers/staging/comedi/drivers/serial2002.c \
../drivers/staging/comedi/drivers/skel.c \
../drivers/staging/comedi/drivers/ssv_dnp.c \
../drivers/staging/comedi/drivers/unioxx5.c \
../drivers/staging/comedi/drivers/usbdux.c \
../drivers/staging/comedi/drivers/usbduxfast.c \
../drivers/staging/comedi/drivers/vmk80xx.c 

OBJS += \
./drivers/staging/comedi/drivers/8255.o \
./drivers/staging/comedi/drivers/acl7225b.o \
./drivers/staging/comedi/drivers/addi_apci_035.o \
./drivers/staging/comedi/drivers/addi_apci_1032.o \
./drivers/staging/comedi/drivers/addi_apci_1500.o \
./drivers/staging/comedi/drivers/addi_apci_1516.o \
./drivers/staging/comedi/drivers/addi_apci_1564.o \
./drivers/staging/comedi/drivers/addi_apci_16xx.o \
./drivers/staging/comedi/drivers/addi_apci_1710.o \
./drivers/staging/comedi/drivers/addi_apci_2016.o \
./drivers/staging/comedi/drivers/addi_apci_2032.o \
./drivers/staging/comedi/drivers/addi_apci_2200.o \
./drivers/staging/comedi/drivers/addi_apci_3001.o \
./drivers/staging/comedi/drivers/addi_apci_3120.o \
./drivers/staging/comedi/drivers/addi_apci_3200.o \
./drivers/staging/comedi/drivers/addi_apci_3300.o \
./drivers/staging/comedi/drivers/addi_apci_3501.o \
./drivers/staging/comedi/drivers/addi_apci_3xxx.o \
./drivers/staging/comedi/drivers/addi_apci_all.o \
./drivers/staging/comedi/drivers/adl_pci6208.o \
./drivers/staging/comedi/drivers/adl_pci7296.o \
./drivers/staging/comedi/drivers/adl_pci7432.o \
./drivers/staging/comedi/drivers/adl_pci8164.o \
./drivers/staging/comedi/drivers/adl_pci9111.o \
./drivers/staging/comedi/drivers/adl_pci9118.o \
./drivers/staging/comedi/drivers/adq12b.o \
./drivers/staging/comedi/drivers/adv_pci1710.o \
./drivers/staging/comedi/drivers/adv_pci1723.o \
./drivers/staging/comedi/drivers/adv_pci_dio.o \
./drivers/staging/comedi/drivers/aio_aio12_8.o \
./drivers/staging/comedi/drivers/aio_iiro_16.o \
./drivers/staging/comedi/drivers/amplc_dio200.o \
./drivers/staging/comedi/drivers/amplc_pc236.o \
./drivers/staging/comedi/drivers/amplc_pc263.o \
./drivers/staging/comedi/drivers/amplc_pci224.o \
./drivers/staging/comedi/drivers/amplc_pci230.o \
./drivers/staging/comedi/drivers/c6xdigio.o \
./drivers/staging/comedi/drivers/cb_das16_cs.o \
./drivers/staging/comedi/drivers/cb_pcidas.o \
./drivers/staging/comedi/drivers/cb_pcidas64.o \
./drivers/staging/comedi/drivers/cb_pcidda.o \
./drivers/staging/comedi/drivers/cb_pcidio.o \
./drivers/staging/comedi/drivers/cb_pcimdas.o \
./drivers/staging/comedi/drivers/cb_pcimdda.o \
./drivers/staging/comedi/drivers/comedi_bond.o \
./drivers/staging/comedi/drivers/comedi_fc.o \
./drivers/staging/comedi/drivers/comedi_parport.o \
./drivers/staging/comedi/drivers/comedi_test.o \
./drivers/staging/comedi/drivers/contec_pci_dio.o \
./drivers/staging/comedi/drivers/daqboard2000.o \
./drivers/staging/comedi/drivers/das08.o \
./drivers/staging/comedi/drivers/das08_cs.o \
./drivers/staging/comedi/drivers/das16.o \
./drivers/staging/comedi/drivers/das16m1.o \
./drivers/staging/comedi/drivers/das1800.o \
./drivers/staging/comedi/drivers/das6402.o \
./drivers/staging/comedi/drivers/das800.o \
./drivers/staging/comedi/drivers/dmm32at.o \
./drivers/staging/comedi/drivers/dt2801.o \
./drivers/staging/comedi/drivers/dt2811.o \
./drivers/staging/comedi/drivers/dt2814.o \
./drivers/staging/comedi/drivers/dt2815.o \
./drivers/staging/comedi/drivers/dt2817.o \
./drivers/staging/comedi/drivers/dt282x.o \
./drivers/staging/comedi/drivers/dt3000.o \
./drivers/staging/comedi/drivers/dt9812.o \
./drivers/staging/comedi/drivers/fl512.o \
./drivers/staging/comedi/drivers/gsc_hpdi.o \
./drivers/staging/comedi/drivers/icp_multi.o \
./drivers/staging/comedi/drivers/ii_pci20kc.o \
./drivers/staging/comedi/drivers/jr3_pci.o \
./drivers/staging/comedi/drivers/ke_counter.o \
./drivers/staging/comedi/drivers/me4000.o \
./drivers/staging/comedi/drivers/me_daq.o \
./drivers/staging/comedi/drivers/mite.o \
./drivers/staging/comedi/drivers/mpc624.o \
./drivers/staging/comedi/drivers/mpc8260cpm.o \
./drivers/staging/comedi/drivers/multiq3.o \
./drivers/staging/comedi/drivers/ni_6527.o \
./drivers/staging/comedi/drivers/ni_65xx.o \
./drivers/staging/comedi/drivers/ni_660x.o \
./drivers/staging/comedi/drivers/ni_670x.o \
./drivers/staging/comedi/drivers/ni_at_a2150.o \
./drivers/staging/comedi/drivers/ni_at_ao.o \
./drivers/staging/comedi/drivers/ni_atmio.o \
./drivers/staging/comedi/drivers/ni_atmio16d.o \
./drivers/staging/comedi/drivers/ni_daq_700.o \
./drivers/staging/comedi/drivers/ni_daq_dio24.o \
./drivers/staging/comedi/drivers/ni_labpc.o \
./drivers/staging/comedi/drivers/ni_labpc_cs.o \
./drivers/staging/comedi/drivers/ni_mio_common.o \
./drivers/staging/comedi/drivers/ni_mio_cs.o \
./drivers/staging/comedi/drivers/ni_pcidio.o \
./drivers/staging/comedi/drivers/ni_pcimio.o \
./drivers/staging/comedi/drivers/ni_tio.o \
./drivers/staging/comedi/drivers/ni_tiocmd.o \
./drivers/staging/comedi/drivers/pcl711.o \
./drivers/staging/comedi/drivers/pcl724.o \
./drivers/staging/comedi/drivers/pcl725.o \
./drivers/staging/comedi/drivers/pcl726.o \
./drivers/staging/comedi/drivers/pcl730.o \
./drivers/staging/comedi/drivers/pcl812.o \
./drivers/staging/comedi/drivers/pcl816.o \
./drivers/staging/comedi/drivers/pcl818.o \
./drivers/staging/comedi/drivers/pcm3724.o \
./drivers/staging/comedi/drivers/pcm3730.o \
./drivers/staging/comedi/drivers/pcm_common.o \
./drivers/staging/comedi/drivers/pcmad.o \
./drivers/staging/comedi/drivers/pcmda12.o \
./drivers/staging/comedi/drivers/pcmmio.o \
./drivers/staging/comedi/drivers/pcmuio.o \
./drivers/staging/comedi/drivers/poc.o \
./drivers/staging/comedi/drivers/quatech_daqp_cs.o \
./drivers/staging/comedi/drivers/rtd520.o \
./drivers/staging/comedi/drivers/rti800.o \
./drivers/staging/comedi/drivers/rti802.o \
./drivers/staging/comedi/drivers/s526.o \
./drivers/staging/comedi/drivers/s626.o \
./drivers/staging/comedi/drivers/serial2002.o \
./drivers/staging/comedi/drivers/skel.o \
./drivers/staging/comedi/drivers/ssv_dnp.o \
./drivers/staging/comedi/drivers/unioxx5.o \
./drivers/staging/comedi/drivers/usbdux.o \
./drivers/staging/comedi/drivers/usbduxfast.o \
./drivers/staging/comedi/drivers/vmk80xx.o 

C_DEPS += \
./drivers/staging/comedi/drivers/8255.d \
./drivers/staging/comedi/drivers/acl7225b.d \
./drivers/staging/comedi/drivers/addi_apci_035.d \
./drivers/staging/comedi/drivers/addi_apci_1032.d \
./drivers/staging/comedi/drivers/addi_apci_1500.d \
./drivers/staging/comedi/drivers/addi_apci_1516.d \
./drivers/staging/comedi/drivers/addi_apci_1564.d \
./drivers/staging/comedi/drivers/addi_apci_16xx.d \
./drivers/staging/comedi/drivers/addi_apci_1710.d \
./drivers/staging/comedi/drivers/addi_apci_2016.d \
./drivers/staging/comedi/drivers/addi_apci_2032.d \
./drivers/staging/comedi/drivers/addi_apci_2200.d \
./drivers/staging/comedi/drivers/addi_apci_3001.d \
./drivers/staging/comedi/drivers/addi_apci_3120.d \
./drivers/staging/comedi/drivers/addi_apci_3200.d \
./drivers/staging/comedi/drivers/addi_apci_3300.d \
./drivers/staging/comedi/drivers/addi_apci_3501.d \
./drivers/staging/comedi/drivers/addi_apci_3xxx.d \
./drivers/staging/comedi/drivers/addi_apci_all.d \
./drivers/staging/comedi/drivers/adl_pci6208.d \
./drivers/staging/comedi/drivers/adl_pci7296.d \
./drivers/staging/comedi/drivers/adl_pci7432.d \
./drivers/staging/comedi/drivers/adl_pci8164.d \
./drivers/staging/comedi/drivers/adl_pci9111.d \
./drivers/staging/comedi/drivers/adl_pci9118.d \
./drivers/staging/comedi/drivers/adq12b.d \
./drivers/staging/comedi/drivers/adv_pci1710.d \
./drivers/staging/comedi/drivers/adv_pci1723.d \
./drivers/staging/comedi/drivers/adv_pci_dio.d \
./drivers/staging/comedi/drivers/aio_aio12_8.d \
./drivers/staging/comedi/drivers/aio_iiro_16.d \
./drivers/staging/comedi/drivers/amplc_dio200.d \
./drivers/staging/comedi/drivers/amplc_pc236.d \
./drivers/staging/comedi/drivers/amplc_pc263.d \
./drivers/staging/comedi/drivers/amplc_pci224.d \
./drivers/staging/comedi/drivers/amplc_pci230.d \
./drivers/staging/comedi/drivers/c6xdigio.d \
./drivers/staging/comedi/drivers/cb_das16_cs.d \
./drivers/staging/comedi/drivers/cb_pcidas.d \
./drivers/staging/comedi/drivers/cb_pcidas64.d \
./drivers/staging/comedi/drivers/cb_pcidda.d \
./drivers/staging/comedi/drivers/cb_pcidio.d \
./drivers/staging/comedi/drivers/cb_pcimdas.d \
./drivers/staging/comedi/drivers/cb_pcimdda.d \
./drivers/staging/comedi/drivers/comedi_bond.d \
./drivers/staging/comedi/drivers/comedi_fc.d \
./drivers/staging/comedi/drivers/comedi_parport.d \
./drivers/staging/comedi/drivers/comedi_test.d \
./drivers/staging/comedi/drivers/contec_pci_dio.d \
./drivers/staging/comedi/drivers/daqboard2000.d \
./drivers/staging/comedi/drivers/das08.d \
./drivers/staging/comedi/drivers/das08_cs.d \
./drivers/staging/comedi/drivers/das16.d \
./drivers/staging/comedi/drivers/das16m1.d \
./drivers/staging/comedi/drivers/das1800.d \
./drivers/staging/comedi/drivers/das6402.d \
./drivers/staging/comedi/drivers/das800.d \
./drivers/staging/comedi/drivers/dmm32at.d \
./drivers/staging/comedi/drivers/dt2801.d \
./drivers/staging/comedi/drivers/dt2811.d \
./drivers/staging/comedi/drivers/dt2814.d \
./drivers/staging/comedi/drivers/dt2815.d \
./drivers/staging/comedi/drivers/dt2817.d \
./drivers/staging/comedi/drivers/dt282x.d \
./drivers/staging/comedi/drivers/dt3000.d \
./drivers/staging/comedi/drivers/dt9812.d \
./drivers/staging/comedi/drivers/fl512.d \
./drivers/staging/comedi/drivers/gsc_hpdi.d \
./drivers/staging/comedi/drivers/icp_multi.d \
./drivers/staging/comedi/drivers/ii_pci20kc.d \
./drivers/staging/comedi/drivers/jr3_pci.d \
./drivers/staging/comedi/drivers/ke_counter.d \
./drivers/staging/comedi/drivers/me4000.d \
./drivers/staging/comedi/drivers/me_daq.d \
./drivers/staging/comedi/drivers/mite.d \
./drivers/staging/comedi/drivers/mpc624.d \
./drivers/staging/comedi/drivers/mpc8260cpm.d \
./drivers/staging/comedi/drivers/multiq3.d \
./drivers/staging/comedi/drivers/ni_6527.d \
./drivers/staging/comedi/drivers/ni_65xx.d \
./drivers/staging/comedi/drivers/ni_660x.d \
./drivers/staging/comedi/drivers/ni_670x.d \
./drivers/staging/comedi/drivers/ni_at_a2150.d \
./drivers/staging/comedi/drivers/ni_at_ao.d \
./drivers/staging/comedi/drivers/ni_atmio.d \
./drivers/staging/comedi/drivers/ni_atmio16d.d \
./drivers/staging/comedi/drivers/ni_daq_700.d \
./drivers/staging/comedi/drivers/ni_daq_dio24.d \
./drivers/staging/comedi/drivers/ni_labpc.d \
./drivers/staging/comedi/drivers/ni_labpc_cs.d \
./drivers/staging/comedi/drivers/ni_mio_common.d \
./drivers/staging/comedi/drivers/ni_mio_cs.d \
./drivers/staging/comedi/drivers/ni_pcidio.d \
./drivers/staging/comedi/drivers/ni_pcimio.d \
./drivers/staging/comedi/drivers/ni_tio.d \
./drivers/staging/comedi/drivers/ni_tiocmd.d \
./drivers/staging/comedi/drivers/pcl711.d \
./drivers/staging/comedi/drivers/pcl724.d \
./drivers/staging/comedi/drivers/pcl725.d \
./drivers/staging/comedi/drivers/pcl726.d \
./drivers/staging/comedi/drivers/pcl730.d \
./drivers/staging/comedi/drivers/pcl812.d \
./drivers/staging/comedi/drivers/pcl816.d \
./drivers/staging/comedi/drivers/pcl818.d \
./drivers/staging/comedi/drivers/pcm3724.d \
./drivers/staging/comedi/drivers/pcm3730.d \
./drivers/staging/comedi/drivers/pcm_common.d \
./drivers/staging/comedi/drivers/pcmad.d \
./drivers/staging/comedi/drivers/pcmda12.d \
./drivers/staging/comedi/drivers/pcmmio.d \
./drivers/staging/comedi/drivers/pcmuio.d \
./drivers/staging/comedi/drivers/poc.d \
./drivers/staging/comedi/drivers/quatech_daqp_cs.d \
./drivers/staging/comedi/drivers/rtd520.d \
./drivers/staging/comedi/drivers/rti800.d \
./drivers/staging/comedi/drivers/rti802.d \
./drivers/staging/comedi/drivers/s526.d \
./drivers/staging/comedi/drivers/s626.d \
./drivers/staging/comedi/drivers/serial2002.d \
./drivers/staging/comedi/drivers/skel.d \
./drivers/staging/comedi/drivers/ssv_dnp.d \
./drivers/staging/comedi/drivers/unioxx5.d \
./drivers/staging/comedi/drivers/usbdux.d \
./drivers/staging/comedi/drivers/usbduxfast.d \
./drivers/staging/comedi/drivers/vmk80xx.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/staging/comedi/drivers/%.o: ../drivers/staging/comedi/drivers/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


