################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/media/video/built-in.o 

C_SRCS += \
../drivers/media/video/adv7170.c \
../drivers/media/video/adv7175.c \
../drivers/media/video/adv7180.c \
../drivers/media/video/adv7343.c \
../drivers/media/video/arv.c \
../drivers/media/video/bt819.c \
../drivers/media/video/bt856.c \
../drivers/media/video/bt866.c \
../drivers/media/video/btcx-risc.c \
../drivers/media/video/bw-qcam.c \
../drivers/media/video/c-qcam.c \
../drivers/media/video/cafe_ccic.c \
../drivers/media/video/cpia.c \
../drivers/media/video/cpia_pp.c \
../drivers/media/video/cpia_usb.c \
../drivers/media/video/cs5345.c \
../drivers/media/video/cs53l32a.c \
../drivers/media/video/cx2341x.c \
../drivers/media/video/dabusb.c \
../drivers/media/video/hexium_gemini.c \
../drivers/media/video/hexium_orion.c \
../drivers/media/video/indycam.c \
../drivers/media/video/ir-kbd-i2c.c \
../drivers/media/video/ks0127.c \
../drivers/media/video/m52790.c \
../drivers/media/video/meye.c \
../drivers/media/video/msp3400-driver.c \
../drivers/media/video/msp3400-kthreads.c \
../drivers/media/video/mt9m001.c \
../drivers/media/video/mt9m111.c \
../drivers/media/video/mt9t031.c \
../drivers/media/video/mt9t112.c \
../drivers/media/video/mt9v011.c \
../drivers/media/video/mt9v022.c \
../drivers/media/video/mx1_camera.c \
../drivers/media/video/mx3_camera.c \
../drivers/media/video/mxb.c \
../drivers/media/video/omap24xxcam-dma.c \
../drivers/media/video/omap24xxcam.c \
../drivers/media/video/ov511.c \
../drivers/media/video/ov7670.c \
../drivers/media/video/ov772x.c \
../drivers/media/video/ov9640.c \
../drivers/media/video/pms.c \
../drivers/media/video/pxa_camera.c \
../drivers/media/video/rj54n1cb0c.c \
../drivers/media/video/s2255drv.c \
../drivers/media/video/saa5246a.c \
../drivers/media/video/saa5249.c \
../drivers/media/video/saa6588.c \
../drivers/media/video/saa7110.c \
../drivers/media/video/saa7115.c \
../drivers/media/video/saa7127.c \
../drivers/media/video/saa717x.c \
../drivers/media/video/saa7185.c \
../drivers/media/video/saa7191.c \
../drivers/media/video/se401.c \
../drivers/media/video/sh_mobile_ceu_camera.c \
../drivers/media/video/soc_camera.c \
../drivers/media/video/soc_camera_platform.c \
../drivers/media/video/soc_mediabus.c \
../drivers/media/video/stk-sensor.c \
../drivers/media/video/stk-webcam.c \
../drivers/media/video/stradis.c \
../drivers/media/video/stv680.c \
../drivers/media/video/tcm825x.c \
../drivers/media/video/tda7432.c \
../drivers/media/video/tda9840.c \
../drivers/media/video/tda9875.c \
../drivers/media/video/tea6415c.c \
../drivers/media/video/tea6420.c \
../drivers/media/video/ths7303.c \
../drivers/media/video/tlv320aic23b.c \
../drivers/media/video/tuner-core.c \
../drivers/media/video/tvaudio.c \
../drivers/media/video/tveeprom.c \
../drivers/media/video/tvp514x.c \
../drivers/media/video/tvp5150.c \
../drivers/media/video/tvp7002.c \
../drivers/media/video/tw9910.c \
../drivers/media/video/upd64031a.c \
../drivers/media/video/upd64083.c \
../drivers/media/video/v4l1-compat.c \
../drivers/media/video/v4l2-common.c \
../drivers/media/video/v4l2-compat-ioctl32.c \
../drivers/media/video/v4l2-dev.c \
../drivers/media/video/v4l2-device.c \
../drivers/media/video/v4l2-int-device.c \
../drivers/media/video/v4l2-ioctl.c \
../drivers/media/video/videobuf-core.c \
../drivers/media/video/videobuf-dma-contig.c \
../drivers/media/video/videobuf-dma-sg.c \
../drivers/media/video/videobuf-dvb.c \
../drivers/media/video/videobuf-vmalloc.c \
../drivers/media/video/vino.c \
../drivers/media/video/vivi.c \
../drivers/media/video/vp27smpx.c \
../drivers/media/video/vpx3220.c \
../drivers/media/video/w9966.c \
../drivers/media/video/w9968cf.c \
../drivers/media/video/wm8739.c \
../drivers/media/video/wm8775.c \
../drivers/media/video/zr364xx.c 

OBJS += \
./drivers/media/video/adv7170.o \
./drivers/media/video/adv7175.o \
./drivers/media/video/adv7180.o \
./drivers/media/video/adv7343.o \
./drivers/media/video/arv.o \
./drivers/media/video/bt819.o \
./drivers/media/video/bt856.o \
./drivers/media/video/bt866.o \
./drivers/media/video/btcx-risc.o \
./drivers/media/video/bw-qcam.o \
./drivers/media/video/c-qcam.o \
./drivers/media/video/cafe_ccic.o \
./drivers/media/video/cpia.o \
./drivers/media/video/cpia_pp.o \
./drivers/media/video/cpia_usb.o \
./drivers/media/video/cs5345.o \
./drivers/media/video/cs53l32a.o \
./drivers/media/video/cx2341x.o \
./drivers/media/video/dabusb.o \
./drivers/media/video/hexium_gemini.o \
./drivers/media/video/hexium_orion.o \
./drivers/media/video/indycam.o \
./drivers/media/video/ir-kbd-i2c.o \
./drivers/media/video/ks0127.o \
./drivers/media/video/m52790.o \
./drivers/media/video/meye.o \
./drivers/media/video/msp3400-driver.o \
./drivers/media/video/msp3400-kthreads.o \
./drivers/media/video/mt9m001.o \
./drivers/media/video/mt9m111.o \
./drivers/media/video/mt9t031.o \
./drivers/media/video/mt9t112.o \
./drivers/media/video/mt9v011.o \
./drivers/media/video/mt9v022.o \
./drivers/media/video/mx1_camera.o \
./drivers/media/video/mx3_camera.o \
./drivers/media/video/mxb.o \
./drivers/media/video/omap24xxcam-dma.o \
./drivers/media/video/omap24xxcam.o \
./drivers/media/video/ov511.o \
./drivers/media/video/ov7670.o \
./drivers/media/video/ov772x.o \
./drivers/media/video/ov9640.o \
./drivers/media/video/pms.o \
./drivers/media/video/pxa_camera.o \
./drivers/media/video/rj54n1cb0c.o \
./drivers/media/video/s2255drv.o \
./drivers/media/video/saa5246a.o \
./drivers/media/video/saa5249.o \
./drivers/media/video/saa6588.o \
./drivers/media/video/saa7110.o \
./drivers/media/video/saa7115.o \
./drivers/media/video/saa7127.o \
./drivers/media/video/saa717x.o \
./drivers/media/video/saa7185.o \
./drivers/media/video/saa7191.o \
./drivers/media/video/se401.o \
./drivers/media/video/sh_mobile_ceu_camera.o \
./drivers/media/video/soc_camera.o \
./drivers/media/video/soc_camera_platform.o \
./drivers/media/video/soc_mediabus.o \
./drivers/media/video/stk-sensor.o \
./drivers/media/video/stk-webcam.o \
./drivers/media/video/stradis.o \
./drivers/media/video/stv680.o \
./drivers/media/video/tcm825x.o \
./drivers/media/video/tda7432.o \
./drivers/media/video/tda9840.o \
./drivers/media/video/tda9875.o \
./drivers/media/video/tea6415c.o \
./drivers/media/video/tea6420.o \
./drivers/media/video/ths7303.o \
./drivers/media/video/tlv320aic23b.o \
./drivers/media/video/tuner-core.o \
./drivers/media/video/tvaudio.o \
./drivers/media/video/tveeprom.o \
./drivers/media/video/tvp514x.o \
./drivers/media/video/tvp5150.o \
./drivers/media/video/tvp7002.o \
./drivers/media/video/tw9910.o \
./drivers/media/video/upd64031a.o \
./drivers/media/video/upd64083.o \
./drivers/media/video/v4l1-compat.o \
./drivers/media/video/v4l2-common.o \
./drivers/media/video/v4l2-compat-ioctl32.o \
./drivers/media/video/v4l2-dev.o \
./drivers/media/video/v4l2-device.o \
./drivers/media/video/v4l2-int-device.o \
./drivers/media/video/v4l2-ioctl.o \
./drivers/media/video/videobuf-core.o \
./drivers/media/video/videobuf-dma-contig.o \
./drivers/media/video/videobuf-dma-sg.o \
./drivers/media/video/videobuf-dvb.o \
./drivers/media/video/videobuf-vmalloc.o \
./drivers/media/video/vino.o \
./drivers/media/video/vivi.o \
./drivers/media/video/vp27smpx.o \
./drivers/media/video/vpx3220.o \
./drivers/media/video/w9966.o \
./drivers/media/video/w9968cf.o \
./drivers/media/video/wm8739.o \
./drivers/media/video/wm8775.o \
./drivers/media/video/zr364xx.o 

C_DEPS += \
./drivers/media/video/adv7170.d \
./drivers/media/video/adv7175.d \
./drivers/media/video/adv7180.d \
./drivers/media/video/adv7343.d \
./drivers/media/video/arv.d \
./drivers/media/video/bt819.d \
./drivers/media/video/bt856.d \
./drivers/media/video/bt866.d \
./drivers/media/video/btcx-risc.d \
./drivers/media/video/bw-qcam.d \
./drivers/media/video/c-qcam.d \
./drivers/media/video/cafe_ccic.d \
./drivers/media/video/cpia.d \
./drivers/media/video/cpia_pp.d \
./drivers/media/video/cpia_usb.d \
./drivers/media/video/cs5345.d \
./drivers/media/video/cs53l32a.d \
./drivers/media/video/cx2341x.d \
./drivers/media/video/dabusb.d \
./drivers/media/video/hexium_gemini.d \
./drivers/media/video/hexium_orion.d \
./drivers/media/video/indycam.d \
./drivers/media/video/ir-kbd-i2c.d \
./drivers/media/video/ks0127.d \
./drivers/media/video/m52790.d \
./drivers/media/video/meye.d \
./drivers/media/video/msp3400-driver.d \
./drivers/media/video/msp3400-kthreads.d \
./drivers/media/video/mt9m001.d \
./drivers/media/video/mt9m111.d \
./drivers/media/video/mt9t031.d \
./drivers/media/video/mt9t112.d \
./drivers/media/video/mt9v011.d \
./drivers/media/video/mt9v022.d \
./drivers/media/video/mx1_camera.d \
./drivers/media/video/mx3_camera.d \
./drivers/media/video/mxb.d \
./drivers/media/video/omap24xxcam-dma.d \
./drivers/media/video/omap24xxcam.d \
./drivers/media/video/ov511.d \
./drivers/media/video/ov7670.d \
./drivers/media/video/ov772x.d \
./drivers/media/video/ov9640.d \
./drivers/media/video/pms.d \
./drivers/media/video/pxa_camera.d \
./drivers/media/video/rj54n1cb0c.d \
./drivers/media/video/s2255drv.d \
./drivers/media/video/saa5246a.d \
./drivers/media/video/saa5249.d \
./drivers/media/video/saa6588.d \
./drivers/media/video/saa7110.d \
./drivers/media/video/saa7115.d \
./drivers/media/video/saa7127.d \
./drivers/media/video/saa717x.d \
./drivers/media/video/saa7185.d \
./drivers/media/video/saa7191.d \
./drivers/media/video/se401.d \
./drivers/media/video/sh_mobile_ceu_camera.d \
./drivers/media/video/soc_camera.d \
./drivers/media/video/soc_camera_platform.d \
./drivers/media/video/soc_mediabus.d \
./drivers/media/video/stk-sensor.d \
./drivers/media/video/stk-webcam.d \
./drivers/media/video/stradis.d \
./drivers/media/video/stv680.d \
./drivers/media/video/tcm825x.d \
./drivers/media/video/tda7432.d \
./drivers/media/video/tda9840.d \
./drivers/media/video/tda9875.d \
./drivers/media/video/tea6415c.d \
./drivers/media/video/tea6420.d \
./drivers/media/video/ths7303.d \
./drivers/media/video/tlv320aic23b.d \
./drivers/media/video/tuner-core.d \
./drivers/media/video/tvaudio.d \
./drivers/media/video/tveeprom.d \
./drivers/media/video/tvp514x.d \
./drivers/media/video/tvp5150.d \
./drivers/media/video/tvp7002.d \
./drivers/media/video/tw9910.d \
./drivers/media/video/upd64031a.d \
./drivers/media/video/upd64083.d \
./drivers/media/video/v4l1-compat.d \
./drivers/media/video/v4l2-common.d \
./drivers/media/video/v4l2-compat-ioctl32.d \
./drivers/media/video/v4l2-dev.d \
./drivers/media/video/v4l2-device.d \
./drivers/media/video/v4l2-int-device.d \
./drivers/media/video/v4l2-ioctl.d \
./drivers/media/video/videobuf-core.d \
./drivers/media/video/videobuf-dma-contig.d \
./drivers/media/video/videobuf-dma-sg.d \
./drivers/media/video/videobuf-dvb.d \
./drivers/media/video/videobuf-vmalloc.d \
./drivers/media/video/vino.d \
./drivers/media/video/vivi.d \
./drivers/media/video/vp27smpx.d \
./drivers/media/video/vpx3220.d \
./drivers/media/video/w9966.d \
./drivers/media/video/w9968cf.d \
./drivers/media/video/wm8739.d \
./drivers/media/video/wm8775.d \
./drivers/media/video/zr364xx.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/media/video/%.o: ../drivers/media/video/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


