################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/net/Space.o \
../drivers/net/built-in.o \
../drivers/net/loopback.o \
../drivers/net/mdio.o 

C_SRCS += \
../drivers/net/3c501.c \
../drivers/net/3c503.c \
../drivers/net/3c505.c \
../drivers/net/3c507.c \
../drivers/net/3c509.c \
../drivers/net/3c515.c \
../drivers/net/3c523.c \
../drivers/net/3c527.c \
../drivers/net/3c59x.c \
../drivers/net/7990.c \
../drivers/net/8139cp.c \
../drivers/net/8139too.c \
../drivers/net/82596.c \
../drivers/net/8390.c \
../drivers/net/8390p.c \
../drivers/net/Space.c \
../drivers/net/a2065.c \
../drivers/net/ac3200.c \
../drivers/net/acenic.c \
../drivers/net/amd8111e.c \
../drivers/net/apne.c \
../drivers/net/ariadne.c \
../drivers/net/at1700.c \
../drivers/net/atarilance.c \
../drivers/net/atp.c \
../drivers/net/au1000_eth.c \
../drivers/net/ax88796.c \
../drivers/net/b44.c \
../drivers/net/bcm63xx_enet.c \
../drivers/net/bfin_mac.c \
../drivers/net/bmac.c \
../drivers/net/bnx2.c \
../drivers/net/bnx2x_link.c \
../drivers/net/bnx2x_main.c \
../drivers/net/bsd_comp.c \
../drivers/net/cassini.c \
../drivers/net/cnic.c \
../drivers/net/cpmac.c \
../drivers/net/cs89x0.c \
../drivers/net/davinci_emac.c \
../drivers/net/de600.c \
../drivers/net/de620.c \
../drivers/net/declance.c \
../drivers/net/defxx.c \
../drivers/net/depca.c \
../drivers/net/dl2k.c \
../drivers/net/dm9000.c \
../drivers/net/dnet.c \
../drivers/net/dummy.c \
../drivers/net/e100.c \
../drivers/net/e2100.c \
../drivers/net/eepro.c \
../drivers/net/eexpress.c \
../drivers/net/enc28j60.c \
../drivers/net/epic100.c \
../drivers/net/eql.c \
../drivers/net/es3210.c \
../drivers/net/eth16i.c \
../drivers/net/ethoc.c \
../drivers/net/ewrk3.c \
../drivers/net/fealnx.c \
../drivers/net/fec.c \
../drivers/net/fec_mpc52xx.c \
../drivers/net/fec_mpc52xx_phy.c \
../drivers/net/forcedeth.c \
../drivers/net/fsl_pq_mdio.c \
../drivers/net/gianfar.c \
../drivers/net/gianfar_ethtool.c \
../drivers/net/gianfar_sysfs.c \
../drivers/net/greth.c \
../drivers/net/hamachi.c \
../drivers/net/hp-plus.c \
../drivers/net/hp.c \
../drivers/net/hp100.c \
../drivers/net/hplance.c \
../drivers/net/hydra.c \
../drivers/net/ibmlana.c \
../drivers/net/ibmveth.c \
../drivers/net/ifb.c \
../drivers/net/ioc3-eth.c \
../drivers/net/ipg.c \
../drivers/net/iseries_veth.c \
../drivers/net/jazzsonic.c \
../drivers/net/jme.c \
../drivers/net/korina.c \
../drivers/net/ks8842.c \
../drivers/net/ks8851.c \
../drivers/net/ks8851_mll.c \
../drivers/net/ksz884x.c \
../drivers/net/lance.c \
../drivers/net/lasi_82596.c \
../drivers/net/lib82596.c \
../drivers/net/lib8390.c \
../drivers/net/ll_temac_main.c \
../drivers/net/ll_temac_mdio.c \
../drivers/net/lne390.c \
../drivers/net/loopback.c \
../drivers/net/lp486e.c \
../drivers/net/mac8390.c \
../drivers/net/mac89x0.c \
../drivers/net/macb.c \
../drivers/net/mace.c \
../drivers/net/macmace.c \
../drivers/net/macsonic.c \
../drivers/net/macvlan.c \
../drivers/net/macvtap.c \
../drivers/net/mdio.c \
../drivers/net/meth.c \
../drivers/net/mii.c \
../drivers/net/mipsnet.c \
../drivers/net/mv643xx_eth.c \
../drivers/net/mvme147.c \
../drivers/net/myri_sbus.c \
../drivers/net/natsemi.c \
../drivers/net/ne-h8300.c \
../drivers/net/ne.c \
../drivers/net/ne2.c \
../drivers/net/ne2k-pci.c \
../drivers/net/ne3210.c \
../drivers/net/netconsole.c \
../drivers/net/netx-eth.c \
../drivers/net/ni5010.c \
../drivers/net/ni52.c \
../drivers/net/ni65.c \
../drivers/net/niu.c \
../drivers/net/ns83820.c \
../drivers/net/pasemi_mac.c \
../drivers/net/pasemi_mac_ethtool.c \
../drivers/net/pci-skeleton.c \
../drivers/net/pcnet32.c \
../drivers/net/plip.c \
../drivers/net/ppp_async.c \
../drivers/net/ppp_deflate.c \
../drivers/net/ppp_generic.c \
../drivers/net/ppp_mppe.c \
../drivers/net/ppp_synctty.c \
../drivers/net/pppoe.c \
../drivers/net/pppol2tp.c \
../drivers/net/pppox.c \
../drivers/net/ps3_gelic_net.c \
../drivers/net/ps3_gelic_wireless.c \
../drivers/net/qla3xxx.c \
../drivers/net/r6040.c \
../drivers/net/r8169.c \
../drivers/net/rionet.c \
../drivers/net/rrunner.c \
../drivers/net/s2io.c \
../drivers/net/s6gmac.c \
../drivers/net/sb1000.c \
../drivers/net/sb1250-mac.c \
../drivers/net/sc92031.c \
../drivers/net/seeq8005.c \
../drivers/net/sgiseeq.c \
../drivers/net/sh_eth.c \
../drivers/net/sis190.c \
../drivers/net/sis900.c \
../drivers/net/skge.c \
../drivers/net/sky2.c \
../drivers/net/slhc.c \
../drivers/net/slip.c \
../drivers/net/smc-mca.c \
../drivers/net/smc-ultra.c \
../drivers/net/smc-ultra32.c \
../drivers/net/smc911x.c \
../drivers/net/smc9194.c \
../drivers/net/smc91x.c \
../drivers/net/smsc911x.c \
../drivers/net/smsc9420.c \
../drivers/net/sni_82596.c \
../drivers/net/sonic.c \
../drivers/net/spider_net.c \
../drivers/net/spider_net_ethtool.c \
../drivers/net/starfire.c \
../drivers/net/stnic.c \
../drivers/net/sun3_82586.c \
../drivers/net/sun3lance.c \
../drivers/net/sunbmac.c \
../drivers/net/sundance.c \
../drivers/net/sungem.c \
../drivers/net/sungem_phy.c \
../drivers/net/sunhme.c \
../drivers/net/sunlance.c \
../drivers/net/sunqe.c \
../drivers/net/sunvnet.c \
../drivers/net/tc35815.c \
../drivers/net/tehuti.c \
../drivers/net/tg3.c \
../drivers/net/tlan.c \
../drivers/net/tsi108_eth.c \
../drivers/net/tun.c \
../drivers/net/typhoon.c \
../drivers/net/ucc_geth.c \
../drivers/net/ucc_geth_ethtool.c \
../drivers/net/veth.c \
../drivers/net/via-rhine.c \
../drivers/net/via-velocity.c \
../drivers/net/virtio_net.c \
../drivers/net/wd.c \
../drivers/net/xen-netfront.c \
../drivers/net/xilinx_emaclite.c \
../drivers/net/xtsonic.c \
../drivers/net/yellowfin.c \
../drivers/net/znet.c \
../drivers/net/zorro8390.c 

OBJS += \
./drivers/net/3c501.o \
./drivers/net/3c503.o \
./drivers/net/3c505.o \
./drivers/net/3c507.o \
./drivers/net/3c509.o \
./drivers/net/3c515.o \
./drivers/net/3c523.o \
./drivers/net/3c527.o \
./drivers/net/3c59x.o \
./drivers/net/7990.o \
./drivers/net/8139cp.o \
./drivers/net/8139too.o \
./drivers/net/82596.o \
./drivers/net/8390.o \
./drivers/net/8390p.o \
./drivers/net/Space.o \
./drivers/net/a2065.o \
./drivers/net/ac3200.o \
./drivers/net/acenic.o \
./drivers/net/amd8111e.o \
./drivers/net/apne.o \
./drivers/net/ariadne.o \
./drivers/net/at1700.o \
./drivers/net/atarilance.o \
./drivers/net/atp.o \
./drivers/net/au1000_eth.o \
./drivers/net/ax88796.o \
./drivers/net/b44.o \
./drivers/net/bcm63xx_enet.o \
./drivers/net/bfin_mac.o \
./drivers/net/bmac.o \
./drivers/net/bnx2.o \
./drivers/net/bnx2x_link.o \
./drivers/net/bnx2x_main.o \
./drivers/net/bsd_comp.o \
./drivers/net/cassini.o \
./drivers/net/cnic.o \
./drivers/net/cpmac.o \
./drivers/net/cs89x0.o \
./drivers/net/davinci_emac.o \
./drivers/net/de600.o \
./drivers/net/de620.o \
./drivers/net/declance.o \
./drivers/net/defxx.o \
./drivers/net/depca.o \
./drivers/net/dl2k.o \
./drivers/net/dm9000.o \
./drivers/net/dnet.o \
./drivers/net/dummy.o \
./drivers/net/e100.o \
./drivers/net/e2100.o \
./drivers/net/eepro.o \
./drivers/net/eexpress.o \
./drivers/net/enc28j60.o \
./drivers/net/epic100.o \
./drivers/net/eql.o \
./drivers/net/es3210.o \
./drivers/net/eth16i.o \
./drivers/net/ethoc.o \
./drivers/net/ewrk3.o \
./drivers/net/fealnx.o \
./drivers/net/fec.o \
./drivers/net/fec_mpc52xx.o \
./drivers/net/fec_mpc52xx_phy.o \
./drivers/net/forcedeth.o \
./drivers/net/fsl_pq_mdio.o \
./drivers/net/gianfar.o \
./drivers/net/gianfar_ethtool.o \
./drivers/net/gianfar_sysfs.o \
./drivers/net/greth.o \
./drivers/net/hamachi.o \
./drivers/net/hp-plus.o \
./drivers/net/hp.o \
./drivers/net/hp100.o \
./drivers/net/hplance.o \
./drivers/net/hydra.o \
./drivers/net/ibmlana.o \
./drivers/net/ibmveth.o \
./drivers/net/ifb.o \
./drivers/net/ioc3-eth.o \
./drivers/net/ipg.o \
./drivers/net/iseries_veth.o \
./drivers/net/jazzsonic.o \
./drivers/net/jme.o \
./drivers/net/korina.o \
./drivers/net/ks8842.o \
./drivers/net/ks8851.o \
./drivers/net/ks8851_mll.o \
./drivers/net/ksz884x.o \
./drivers/net/lance.o \
./drivers/net/lasi_82596.o \
./drivers/net/lib82596.o \
./drivers/net/lib8390.o \
./drivers/net/ll_temac_main.o \
./drivers/net/ll_temac_mdio.o \
./drivers/net/lne390.o \
./drivers/net/loopback.o \
./drivers/net/lp486e.o \
./drivers/net/mac8390.o \
./drivers/net/mac89x0.o \
./drivers/net/macb.o \
./drivers/net/mace.o \
./drivers/net/macmace.o \
./drivers/net/macsonic.o \
./drivers/net/macvlan.o \
./drivers/net/macvtap.o \
./drivers/net/mdio.o \
./drivers/net/meth.o \
./drivers/net/mii.o \
./drivers/net/mipsnet.o \
./drivers/net/mv643xx_eth.o \
./drivers/net/mvme147.o \
./drivers/net/myri_sbus.o \
./drivers/net/natsemi.o \
./drivers/net/ne-h8300.o \
./drivers/net/ne.o \
./drivers/net/ne2.o \
./drivers/net/ne2k-pci.o \
./drivers/net/ne3210.o \
./drivers/net/netconsole.o \
./drivers/net/netx-eth.o \
./drivers/net/ni5010.o \
./drivers/net/ni52.o \
./drivers/net/ni65.o \
./drivers/net/niu.o \
./drivers/net/ns83820.o \
./drivers/net/pasemi_mac.o \
./drivers/net/pasemi_mac_ethtool.o \
./drivers/net/pci-skeleton.o \
./drivers/net/pcnet32.o \
./drivers/net/plip.o \
./drivers/net/ppp_async.o \
./drivers/net/ppp_deflate.o \
./drivers/net/ppp_generic.o \
./drivers/net/ppp_mppe.o \
./drivers/net/ppp_synctty.o \
./drivers/net/pppoe.o \
./drivers/net/pppol2tp.o \
./drivers/net/pppox.o \
./drivers/net/ps3_gelic_net.o \
./drivers/net/ps3_gelic_wireless.o \
./drivers/net/qla3xxx.o \
./drivers/net/r6040.o \
./drivers/net/r8169.o \
./drivers/net/rionet.o \
./drivers/net/rrunner.o \
./drivers/net/s2io.o \
./drivers/net/s6gmac.o \
./drivers/net/sb1000.o \
./drivers/net/sb1250-mac.o \
./drivers/net/sc92031.o \
./drivers/net/seeq8005.o \
./drivers/net/sgiseeq.o \
./drivers/net/sh_eth.o \
./drivers/net/sis190.o \
./drivers/net/sis900.o \
./drivers/net/skge.o \
./drivers/net/sky2.o \
./drivers/net/slhc.o \
./drivers/net/slip.o \
./drivers/net/smc-mca.o \
./drivers/net/smc-ultra.o \
./drivers/net/smc-ultra32.o \
./drivers/net/smc911x.o \
./drivers/net/smc9194.o \
./drivers/net/smc91x.o \
./drivers/net/smsc911x.o \
./drivers/net/smsc9420.o \
./drivers/net/sni_82596.o \
./drivers/net/sonic.o \
./drivers/net/spider_net.o \
./drivers/net/spider_net_ethtool.o \
./drivers/net/starfire.o \
./drivers/net/stnic.o \
./drivers/net/sun3_82586.o \
./drivers/net/sun3lance.o \
./drivers/net/sunbmac.o \
./drivers/net/sundance.o \
./drivers/net/sungem.o \
./drivers/net/sungem_phy.o \
./drivers/net/sunhme.o \
./drivers/net/sunlance.o \
./drivers/net/sunqe.o \
./drivers/net/sunvnet.o \
./drivers/net/tc35815.o \
./drivers/net/tehuti.o \
./drivers/net/tg3.o \
./drivers/net/tlan.o \
./drivers/net/tsi108_eth.o \
./drivers/net/tun.o \
./drivers/net/typhoon.o \
./drivers/net/ucc_geth.o \
./drivers/net/ucc_geth_ethtool.o \
./drivers/net/veth.o \
./drivers/net/via-rhine.o \
./drivers/net/via-velocity.o \
./drivers/net/virtio_net.o \
./drivers/net/wd.o \
./drivers/net/xen-netfront.o \
./drivers/net/xilinx_emaclite.o \
./drivers/net/xtsonic.o \
./drivers/net/yellowfin.o \
./drivers/net/znet.o \
./drivers/net/zorro8390.o 

C_DEPS += \
./drivers/net/3c501.d \
./drivers/net/3c503.d \
./drivers/net/3c505.d \
./drivers/net/3c507.d \
./drivers/net/3c509.d \
./drivers/net/3c515.d \
./drivers/net/3c523.d \
./drivers/net/3c527.d \
./drivers/net/3c59x.d \
./drivers/net/7990.d \
./drivers/net/8139cp.d \
./drivers/net/8139too.d \
./drivers/net/82596.d \
./drivers/net/8390.d \
./drivers/net/8390p.d \
./drivers/net/Space.d \
./drivers/net/a2065.d \
./drivers/net/ac3200.d \
./drivers/net/acenic.d \
./drivers/net/amd8111e.d \
./drivers/net/apne.d \
./drivers/net/ariadne.d \
./drivers/net/at1700.d \
./drivers/net/atarilance.d \
./drivers/net/atp.d \
./drivers/net/au1000_eth.d \
./drivers/net/ax88796.d \
./drivers/net/b44.d \
./drivers/net/bcm63xx_enet.d \
./drivers/net/bfin_mac.d \
./drivers/net/bmac.d \
./drivers/net/bnx2.d \
./drivers/net/bnx2x_link.d \
./drivers/net/bnx2x_main.d \
./drivers/net/bsd_comp.d \
./drivers/net/cassini.d \
./drivers/net/cnic.d \
./drivers/net/cpmac.d \
./drivers/net/cs89x0.d \
./drivers/net/davinci_emac.d \
./drivers/net/de600.d \
./drivers/net/de620.d \
./drivers/net/declance.d \
./drivers/net/defxx.d \
./drivers/net/depca.d \
./drivers/net/dl2k.d \
./drivers/net/dm9000.d \
./drivers/net/dnet.d \
./drivers/net/dummy.d \
./drivers/net/e100.d \
./drivers/net/e2100.d \
./drivers/net/eepro.d \
./drivers/net/eexpress.d \
./drivers/net/enc28j60.d \
./drivers/net/epic100.d \
./drivers/net/eql.d \
./drivers/net/es3210.d \
./drivers/net/eth16i.d \
./drivers/net/ethoc.d \
./drivers/net/ewrk3.d \
./drivers/net/fealnx.d \
./drivers/net/fec.d \
./drivers/net/fec_mpc52xx.d \
./drivers/net/fec_mpc52xx_phy.d \
./drivers/net/forcedeth.d \
./drivers/net/fsl_pq_mdio.d \
./drivers/net/gianfar.d \
./drivers/net/gianfar_ethtool.d \
./drivers/net/gianfar_sysfs.d \
./drivers/net/greth.d \
./drivers/net/hamachi.d \
./drivers/net/hp-plus.d \
./drivers/net/hp.d \
./drivers/net/hp100.d \
./drivers/net/hplance.d \
./drivers/net/hydra.d \
./drivers/net/ibmlana.d \
./drivers/net/ibmveth.d \
./drivers/net/ifb.d \
./drivers/net/ioc3-eth.d \
./drivers/net/ipg.d \
./drivers/net/iseries_veth.d \
./drivers/net/jazzsonic.d \
./drivers/net/jme.d \
./drivers/net/korina.d \
./drivers/net/ks8842.d \
./drivers/net/ks8851.d \
./drivers/net/ks8851_mll.d \
./drivers/net/ksz884x.d \
./drivers/net/lance.d \
./drivers/net/lasi_82596.d \
./drivers/net/lib82596.d \
./drivers/net/lib8390.d \
./drivers/net/ll_temac_main.d \
./drivers/net/ll_temac_mdio.d \
./drivers/net/lne390.d \
./drivers/net/loopback.d \
./drivers/net/lp486e.d \
./drivers/net/mac8390.d \
./drivers/net/mac89x0.d \
./drivers/net/macb.d \
./drivers/net/mace.d \
./drivers/net/macmace.d \
./drivers/net/macsonic.d \
./drivers/net/macvlan.d \
./drivers/net/macvtap.d \
./drivers/net/mdio.d \
./drivers/net/meth.d \
./drivers/net/mii.d \
./drivers/net/mipsnet.d \
./drivers/net/mv643xx_eth.d \
./drivers/net/mvme147.d \
./drivers/net/myri_sbus.d \
./drivers/net/natsemi.d \
./drivers/net/ne-h8300.d \
./drivers/net/ne.d \
./drivers/net/ne2.d \
./drivers/net/ne2k-pci.d \
./drivers/net/ne3210.d \
./drivers/net/netconsole.d \
./drivers/net/netx-eth.d \
./drivers/net/ni5010.d \
./drivers/net/ni52.d \
./drivers/net/ni65.d \
./drivers/net/niu.d \
./drivers/net/ns83820.d \
./drivers/net/pasemi_mac.d \
./drivers/net/pasemi_mac_ethtool.d \
./drivers/net/pci-skeleton.d \
./drivers/net/pcnet32.d \
./drivers/net/plip.d \
./drivers/net/ppp_async.d \
./drivers/net/ppp_deflate.d \
./drivers/net/ppp_generic.d \
./drivers/net/ppp_mppe.d \
./drivers/net/ppp_synctty.d \
./drivers/net/pppoe.d \
./drivers/net/pppol2tp.d \
./drivers/net/pppox.d \
./drivers/net/ps3_gelic_net.d \
./drivers/net/ps3_gelic_wireless.d \
./drivers/net/qla3xxx.d \
./drivers/net/r6040.d \
./drivers/net/r8169.d \
./drivers/net/rionet.d \
./drivers/net/rrunner.d \
./drivers/net/s2io.d \
./drivers/net/s6gmac.d \
./drivers/net/sb1000.d \
./drivers/net/sb1250-mac.d \
./drivers/net/sc92031.d \
./drivers/net/seeq8005.d \
./drivers/net/sgiseeq.d \
./drivers/net/sh_eth.d \
./drivers/net/sis190.d \
./drivers/net/sis900.d \
./drivers/net/skge.d \
./drivers/net/sky2.d \
./drivers/net/slhc.d \
./drivers/net/slip.d \
./drivers/net/smc-mca.d \
./drivers/net/smc-ultra.d \
./drivers/net/smc-ultra32.d \
./drivers/net/smc911x.d \
./drivers/net/smc9194.d \
./drivers/net/smc91x.d \
./drivers/net/smsc911x.d \
./drivers/net/smsc9420.d \
./drivers/net/sni_82596.d \
./drivers/net/sonic.d \
./drivers/net/spider_net.d \
./drivers/net/spider_net_ethtool.d \
./drivers/net/starfire.d \
./drivers/net/stnic.d \
./drivers/net/sun3_82586.d \
./drivers/net/sun3lance.d \
./drivers/net/sunbmac.d \
./drivers/net/sundance.d \
./drivers/net/sungem.d \
./drivers/net/sungem_phy.d \
./drivers/net/sunhme.d \
./drivers/net/sunlance.d \
./drivers/net/sunqe.d \
./drivers/net/sunvnet.d \
./drivers/net/tc35815.d \
./drivers/net/tehuti.d \
./drivers/net/tg3.d \
./drivers/net/tlan.d \
./drivers/net/tsi108_eth.d \
./drivers/net/tun.d \
./drivers/net/typhoon.d \
./drivers/net/ucc_geth.d \
./drivers/net/ucc_geth_ethtool.d \
./drivers/net/veth.d \
./drivers/net/via-rhine.d \
./drivers/net/via-velocity.d \
./drivers/net/virtio_net.d \
./drivers/net/wd.d \
./drivers/net/xen-netfront.d \
./drivers/net/xilinx_emaclite.d \
./drivers/net/xtsonic.d \
./drivers/net/yellowfin.d \
./drivers/net/znet.d \
./drivers/net/zorro8390.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/net/%.o: ../drivers/net/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


