################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/scsi/built-in.o \
../drivers/scsi/constants.o \
../drivers/scsi/hosts.o \
../drivers/scsi/scsi.o \
../drivers/scsi/scsi_devinfo.o \
../drivers/scsi/scsi_error.o \
../drivers/scsi/scsi_ioctl.o \
../drivers/scsi/scsi_lib.o \
../drivers/scsi/scsi_lib_dma.o \
../drivers/scsi/scsi_mod.o \
../drivers/scsi/scsi_netlink.o \
../drivers/scsi/scsi_scan.o \
../drivers/scsi/scsi_sysctl.o \
../drivers/scsi/scsi_sysfs.o \
../drivers/scsi/scsi_transport_fc.mod.o \
../drivers/scsi/scsi_transport_fc.o \
../drivers/scsi/scsi_transport_iscsi.mod.o \
../drivers/scsi/scsi_transport_iscsi.o \
../drivers/scsi/scsi_transport_sas.mod.o \
../drivers/scsi/scsi_transport_sas.o \
../drivers/scsi/scsi_transport_spi.o \
../drivers/scsi/scsi_transport_srp.mod.o \
../drivers/scsi/scsi_transport_srp.o \
../drivers/scsi/scsi_wait_scan.mod.o \
../drivers/scsi/scsi_wait_scan.o \
../drivers/scsi/scsicam.o 

C_SRCS += \
../drivers/scsi/3w-9xxx.c \
../drivers/scsi/3w-sas.c \
../drivers/scsi/3w-xxxx.c \
../drivers/scsi/53c700.c \
../drivers/scsi/BusLogic.c \
../drivers/scsi/FlashPoint.c \
../drivers/scsi/NCR5380.c \
../drivers/scsi/NCR53c406a.c \
../drivers/scsi/NCR_D700.c \
../drivers/scsi/NCR_Q720.c \
../drivers/scsi/a100u2w.c \
../drivers/scsi/a2091.c \
../drivers/scsi/a3000.c \
../drivers/scsi/a4000t.c \
../drivers/scsi/advansys.c \
../drivers/scsi/aha152x.c \
../drivers/scsi/aha1542.c \
../drivers/scsi/aha1740.c \
../drivers/scsi/aic7xxx_old.c \
../drivers/scsi/atari_NCR5380.c \
../drivers/scsi/atari_scsi.c \
../drivers/scsi/atp870u.c \
../drivers/scsi/bvme6000_scsi.c \
../drivers/scsi/ch.c \
../drivers/scsi/constants.c \
../drivers/scsi/dc395x.c \
../drivers/scsi/dmx3191d.c \
../drivers/scsi/dpt_i2o.c \
../drivers/scsi/dtc.c \
../drivers/scsi/eata.c \
../drivers/scsi/eata_pio.c \
../drivers/scsi/esp_scsi.c \
../drivers/scsi/fd_mcs.c \
../drivers/scsi/fdomain.c \
../drivers/scsi/g_NCR5380.c \
../drivers/scsi/g_NCR5380_mmio.c \
../drivers/scsi/gdth.c \
../drivers/scsi/gdth_proc.c \
../drivers/scsi/gvp11.c \
../drivers/scsi/hosts.c \
../drivers/scsi/hpsa.c \
../drivers/scsi/hptiop.c \
../drivers/scsi/ibmmca.c \
../drivers/scsi/imm.c \
../drivers/scsi/in2000.c \
../drivers/scsi/initio.c \
../drivers/scsi/ipr.c \
../drivers/scsi/ips.c \
../drivers/scsi/iscsi_tcp.c \
../drivers/scsi/jazz_esp.c \
../drivers/scsi/lasi700.c \
../drivers/scsi/libiscsi.c \
../drivers/scsi/libiscsi_tcp.c \
../drivers/scsi/libsrp.c \
../drivers/scsi/mac53c94.c \
../drivers/scsi/mac_esp.c \
../drivers/scsi/mac_scsi.c \
../drivers/scsi/megaraid.c \
../drivers/scsi/mesh.c \
../drivers/scsi/mvme147.c \
../drivers/scsi/mvme16x_scsi.c \
../drivers/scsi/ncr53c8xx.c \
../drivers/scsi/nsp32.c \
../drivers/scsi/nsp32_debug.c \
../drivers/scsi/osst.c \
../drivers/scsi/pas16.c \
../drivers/scsi/pmcraid.c \
../drivers/scsi/ppa.c \
../drivers/scsi/ps3rom.c \
../drivers/scsi/qla1280.c \
../drivers/scsi/qlogicfas.c \
../drivers/scsi/qlogicfas408.c \
../drivers/scsi/qlogicpti.c \
../drivers/scsi/raid_class.c \
../drivers/scsi/scsi.c \
../drivers/scsi/scsi_debug.c \
../drivers/scsi/scsi_devinfo.c \
../drivers/scsi/scsi_error.c \
../drivers/scsi/scsi_ioctl.c \
../drivers/scsi/scsi_lib.c \
../drivers/scsi/scsi_lib_dma.c \
../drivers/scsi/scsi_module.c \
../drivers/scsi/scsi_netlink.c \
../drivers/scsi/scsi_proc.c \
../drivers/scsi/scsi_scan.c \
../drivers/scsi/scsi_sysctl.c \
../drivers/scsi/scsi_sysfs.c \
../drivers/scsi/scsi_tgt_if.c \
../drivers/scsi/scsi_tgt_lib.c \
../drivers/scsi/scsi_transport_fc.c \
../drivers/scsi/scsi_transport_fc.mod.c \
../drivers/scsi/scsi_transport_iscsi.c \
../drivers/scsi/scsi_transport_iscsi.mod.c \
../drivers/scsi/scsi_transport_sas.c \
../drivers/scsi/scsi_transport_sas.mod.c \
../drivers/scsi/scsi_transport_spi.c \
../drivers/scsi/scsi_transport_srp.c \
../drivers/scsi/scsi_transport_srp.mod.c \
../drivers/scsi/scsi_wait_scan.c \
../drivers/scsi/scsi_wait_scan.mod.c \
../drivers/scsi/scsicam.c \
../drivers/scsi/sd.c \
../drivers/scsi/sd_dif.c \
../drivers/scsi/ses.c \
../drivers/scsi/sg.c \
../drivers/scsi/sgiwd93.c \
../drivers/scsi/sim710.c \
../drivers/scsi/sni_53c710.c \
../drivers/scsi/sr.c \
../drivers/scsi/sr_ioctl.c \
../drivers/scsi/sr_vendor.c \
../drivers/scsi/st.c \
../drivers/scsi/stex.c \
../drivers/scsi/sun3_NCR5380.c \
../drivers/scsi/sun3_scsi.c \
../drivers/scsi/sun3_scsi_vme.c \
../drivers/scsi/sun3x_esp.c \
../drivers/scsi/sun_esp.c \
../drivers/scsi/sym53c416.c \
../drivers/scsi/t128.c \
../drivers/scsi/tmscsim.c \
../drivers/scsi/u14-34f.c \
../drivers/scsi/ultrastor.c \
../drivers/scsi/vmw_pvscsi.c \
../drivers/scsi/wd33c93.c \
../drivers/scsi/wd7000.c \
../drivers/scsi/zalon.c \
../drivers/scsi/zorro7xx.c 

OBJS += \
./drivers/scsi/3w-9xxx.o \
./drivers/scsi/3w-sas.o \
./drivers/scsi/3w-xxxx.o \
./drivers/scsi/53c700.o \
./drivers/scsi/BusLogic.o \
./drivers/scsi/FlashPoint.o \
./drivers/scsi/NCR5380.o \
./drivers/scsi/NCR53c406a.o \
./drivers/scsi/NCR_D700.o \
./drivers/scsi/NCR_Q720.o \
./drivers/scsi/a100u2w.o \
./drivers/scsi/a2091.o \
./drivers/scsi/a3000.o \
./drivers/scsi/a4000t.o \
./drivers/scsi/advansys.o \
./drivers/scsi/aha152x.o \
./drivers/scsi/aha1542.o \
./drivers/scsi/aha1740.o \
./drivers/scsi/aic7xxx_old.o \
./drivers/scsi/atari_NCR5380.o \
./drivers/scsi/atari_scsi.o \
./drivers/scsi/atp870u.o \
./drivers/scsi/bvme6000_scsi.o \
./drivers/scsi/ch.o \
./drivers/scsi/constants.o \
./drivers/scsi/dc395x.o \
./drivers/scsi/dmx3191d.o \
./drivers/scsi/dpt_i2o.o \
./drivers/scsi/dtc.o \
./drivers/scsi/eata.o \
./drivers/scsi/eata_pio.o \
./drivers/scsi/esp_scsi.o \
./drivers/scsi/fd_mcs.o \
./drivers/scsi/fdomain.o \
./drivers/scsi/g_NCR5380.o \
./drivers/scsi/g_NCR5380_mmio.o \
./drivers/scsi/gdth.o \
./drivers/scsi/gdth_proc.o \
./drivers/scsi/gvp11.o \
./drivers/scsi/hosts.o \
./drivers/scsi/hpsa.o \
./drivers/scsi/hptiop.o \
./drivers/scsi/ibmmca.o \
./drivers/scsi/imm.o \
./drivers/scsi/in2000.o \
./drivers/scsi/initio.o \
./drivers/scsi/ipr.o \
./drivers/scsi/ips.o \
./drivers/scsi/iscsi_tcp.o \
./drivers/scsi/jazz_esp.o \
./drivers/scsi/lasi700.o \
./drivers/scsi/libiscsi.o \
./drivers/scsi/libiscsi_tcp.o \
./drivers/scsi/libsrp.o \
./drivers/scsi/mac53c94.o \
./drivers/scsi/mac_esp.o \
./drivers/scsi/mac_scsi.o \
./drivers/scsi/megaraid.o \
./drivers/scsi/mesh.o \
./drivers/scsi/mvme147.o \
./drivers/scsi/mvme16x_scsi.o \
./drivers/scsi/ncr53c8xx.o \
./drivers/scsi/nsp32.o \
./drivers/scsi/nsp32_debug.o \
./drivers/scsi/osst.o \
./drivers/scsi/pas16.o \
./drivers/scsi/pmcraid.o \
./drivers/scsi/ppa.o \
./drivers/scsi/ps3rom.o \
./drivers/scsi/qla1280.o \
./drivers/scsi/qlogicfas.o \
./drivers/scsi/qlogicfas408.o \
./drivers/scsi/qlogicpti.o \
./drivers/scsi/raid_class.o \
./drivers/scsi/scsi.o \
./drivers/scsi/scsi_debug.o \
./drivers/scsi/scsi_devinfo.o \
./drivers/scsi/scsi_error.o \
./drivers/scsi/scsi_ioctl.o \
./drivers/scsi/scsi_lib.o \
./drivers/scsi/scsi_lib_dma.o \
./drivers/scsi/scsi_module.o \
./drivers/scsi/scsi_netlink.o \
./drivers/scsi/scsi_proc.o \
./drivers/scsi/scsi_scan.o \
./drivers/scsi/scsi_sysctl.o \
./drivers/scsi/scsi_sysfs.o \
./drivers/scsi/scsi_tgt_if.o \
./drivers/scsi/scsi_tgt_lib.o \
./drivers/scsi/scsi_transport_fc.o \
./drivers/scsi/scsi_transport_fc.mod.o \
./drivers/scsi/scsi_transport_iscsi.o \
./drivers/scsi/scsi_transport_iscsi.mod.o \
./drivers/scsi/scsi_transport_sas.o \
./drivers/scsi/scsi_transport_sas.mod.o \
./drivers/scsi/scsi_transport_spi.o \
./drivers/scsi/scsi_transport_srp.o \
./drivers/scsi/scsi_transport_srp.mod.o \
./drivers/scsi/scsi_wait_scan.o \
./drivers/scsi/scsi_wait_scan.mod.o \
./drivers/scsi/scsicam.o \
./drivers/scsi/sd.o \
./drivers/scsi/sd_dif.o \
./drivers/scsi/ses.o \
./drivers/scsi/sg.o \
./drivers/scsi/sgiwd93.o \
./drivers/scsi/sim710.o \
./drivers/scsi/sni_53c710.o \
./drivers/scsi/sr.o \
./drivers/scsi/sr_ioctl.o \
./drivers/scsi/sr_vendor.o \
./drivers/scsi/st.o \
./drivers/scsi/stex.o \
./drivers/scsi/sun3_NCR5380.o \
./drivers/scsi/sun3_scsi.o \
./drivers/scsi/sun3_scsi_vme.o \
./drivers/scsi/sun3x_esp.o \
./drivers/scsi/sun_esp.o \
./drivers/scsi/sym53c416.o \
./drivers/scsi/t128.o \
./drivers/scsi/tmscsim.o \
./drivers/scsi/u14-34f.o \
./drivers/scsi/ultrastor.o \
./drivers/scsi/vmw_pvscsi.o \
./drivers/scsi/wd33c93.o \
./drivers/scsi/wd7000.o \
./drivers/scsi/zalon.o \
./drivers/scsi/zorro7xx.o 

C_DEPS += \
./drivers/scsi/3w-9xxx.d \
./drivers/scsi/3w-sas.d \
./drivers/scsi/3w-xxxx.d \
./drivers/scsi/53c700.d \
./drivers/scsi/BusLogic.d \
./drivers/scsi/FlashPoint.d \
./drivers/scsi/NCR5380.d \
./drivers/scsi/NCR53c406a.d \
./drivers/scsi/NCR_D700.d \
./drivers/scsi/NCR_Q720.d \
./drivers/scsi/a100u2w.d \
./drivers/scsi/a2091.d \
./drivers/scsi/a3000.d \
./drivers/scsi/a4000t.d \
./drivers/scsi/advansys.d \
./drivers/scsi/aha152x.d \
./drivers/scsi/aha1542.d \
./drivers/scsi/aha1740.d \
./drivers/scsi/aic7xxx_old.d \
./drivers/scsi/atari_NCR5380.d \
./drivers/scsi/atari_scsi.d \
./drivers/scsi/atp870u.d \
./drivers/scsi/bvme6000_scsi.d \
./drivers/scsi/ch.d \
./drivers/scsi/constants.d \
./drivers/scsi/dc395x.d \
./drivers/scsi/dmx3191d.d \
./drivers/scsi/dpt_i2o.d \
./drivers/scsi/dtc.d \
./drivers/scsi/eata.d \
./drivers/scsi/eata_pio.d \
./drivers/scsi/esp_scsi.d \
./drivers/scsi/fd_mcs.d \
./drivers/scsi/fdomain.d \
./drivers/scsi/g_NCR5380.d \
./drivers/scsi/g_NCR5380_mmio.d \
./drivers/scsi/gdth.d \
./drivers/scsi/gdth_proc.d \
./drivers/scsi/gvp11.d \
./drivers/scsi/hosts.d \
./drivers/scsi/hpsa.d \
./drivers/scsi/hptiop.d \
./drivers/scsi/ibmmca.d \
./drivers/scsi/imm.d \
./drivers/scsi/in2000.d \
./drivers/scsi/initio.d \
./drivers/scsi/ipr.d \
./drivers/scsi/ips.d \
./drivers/scsi/iscsi_tcp.d \
./drivers/scsi/jazz_esp.d \
./drivers/scsi/lasi700.d \
./drivers/scsi/libiscsi.d \
./drivers/scsi/libiscsi_tcp.d \
./drivers/scsi/libsrp.d \
./drivers/scsi/mac53c94.d \
./drivers/scsi/mac_esp.d \
./drivers/scsi/mac_scsi.d \
./drivers/scsi/megaraid.d \
./drivers/scsi/mesh.d \
./drivers/scsi/mvme147.d \
./drivers/scsi/mvme16x_scsi.d \
./drivers/scsi/ncr53c8xx.d \
./drivers/scsi/nsp32.d \
./drivers/scsi/nsp32_debug.d \
./drivers/scsi/osst.d \
./drivers/scsi/pas16.d \
./drivers/scsi/pmcraid.d \
./drivers/scsi/ppa.d \
./drivers/scsi/ps3rom.d \
./drivers/scsi/qla1280.d \
./drivers/scsi/qlogicfas.d \
./drivers/scsi/qlogicfas408.d \
./drivers/scsi/qlogicpti.d \
./drivers/scsi/raid_class.d \
./drivers/scsi/scsi.d \
./drivers/scsi/scsi_debug.d \
./drivers/scsi/scsi_devinfo.d \
./drivers/scsi/scsi_error.d \
./drivers/scsi/scsi_ioctl.d \
./drivers/scsi/scsi_lib.d \
./drivers/scsi/scsi_lib_dma.d \
./drivers/scsi/scsi_module.d \
./drivers/scsi/scsi_netlink.d \
./drivers/scsi/scsi_proc.d \
./drivers/scsi/scsi_scan.d \
./drivers/scsi/scsi_sysctl.d \
./drivers/scsi/scsi_sysfs.d \
./drivers/scsi/scsi_tgt_if.d \
./drivers/scsi/scsi_tgt_lib.d \
./drivers/scsi/scsi_transport_fc.d \
./drivers/scsi/scsi_transport_fc.mod.d \
./drivers/scsi/scsi_transport_iscsi.d \
./drivers/scsi/scsi_transport_iscsi.mod.d \
./drivers/scsi/scsi_transport_sas.d \
./drivers/scsi/scsi_transport_sas.mod.d \
./drivers/scsi/scsi_transport_spi.d \
./drivers/scsi/scsi_transport_srp.d \
./drivers/scsi/scsi_transport_srp.mod.d \
./drivers/scsi/scsi_wait_scan.d \
./drivers/scsi/scsi_wait_scan.mod.d \
./drivers/scsi/scsicam.d \
./drivers/scsi/sd.d \
./drivers/scsi/sd_dif.d \
./drivers/scsi/ses.d \
./drivers/scsi/sg.d \
./drivers/scsi/sgiwd93.d \
./drivers/scsi/sim710.d \
./drivers/scsi/sni_53c710.d \
./drivers/scsi/sr.d \
./drivers/scsi/sr_ioctl.d \
./drivers/scsi/sr_vendor.d \
./drivers/scsi/st.d \
./drivers/scsi/stex.d \
./drivers/scsi/sun3_NCR5380.d \
./drivers/scsi/sun3_scsi.d \
./drivers/scsi/sun3_scsi_vme.d \
./drivers/scsi/sun3x_esp.d \
./drivers/scsi/sun_esp.d \
./drivers/scsi/sym53c416.d \
./drivers/scsi/t128.d \
./drivers/scsi/tmscsim.d \
./drivers/scsi/u14-34f.d \
./drivers/scsi/ultrastor.d \
./drivers/scsi/vmw_pvscsi.d \
./drivers/scsi/wd33c93.d \
./drivers/scsi/wd7000.d \
./drivers/scsi/zalon.d \
./drivers/scsi/zorro7xx.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/scsi/%.o: ../drivers/scsi/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


