################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../net/ipv4/af_inet.o \
../net/ipv4/arp.o \
../net/ipv4/built-in.o \
../net/ipv4/datagram.o \
../net/ipv4/devinet.o \
../net/ipv4/fib_frontend.o \
../net/ipv4/fib_hash.o \
../net/ipv4/fib_semantics.o \
../net/ipv4/icmp.o \
../net/ipv4/igmp.o \
../net/ipv4/inet_connection_sock.o \
../net/ipv4/inet_fragment.o \
../net/ipv4/inet_hashtables.o \
../net/ipv4/inet_lro.o \
../net/ipv4/inet_timewait_sock.o \
../net/ipv4/inetpeer.o \
../net/ipv4/ip_forward.o \
../net/ipv4/ip_fragment.o \
../net/ipv4/ip_input.o \
../net/ipv4/ip_options.o \
../net/ipv4/ip_output.o \
../net/ipv4/ip_sockglue.o \
../net/ipv4/ipconfig.o \
../net/ipv4/proc.o \
../net/ipv4/protocol.o \
../net/ipv4/raw.o \
../net/ipv4/route.o \
../net/ipv4/sysctl_net_ipv4.o \
../net/ipv4/tcp.o \
../net/ipv4/tcp_cong.o \
../net/ipv4/tcp_cubic.o \
../net/ipv4/tcp_input.o \
../net/ipv4/tcp_ipv4.o \
../net/ipv4/tcp_minisocks.o \
../net/ipv4/tcp_output.o \
../net/ipv4/tcp_timer.o \
../net/ipv4/udp.o \
../net/ipv4/udplite.o \
../net/ipv4/xfrm4_input.o \
../net/ipv4/xfrm4_output.o \
../net/ipv4/xfrm4_policy.o \
../net/ipv4/xfrm4_state.o 

C_SRCS += \
../net/ipv4/af_inet.c \
../net/ipv4/ah4.c \
../net/ipv4/arp.c \
../net/ipv4/cipso_ipv4.c \
../net/ipv4/datagram.c \
../net/ipv4/devinet.c \
../net/ipv4/esp4.c \
../net/ipv4/fib_frontend.c \
../net/ipv4/fib_hash.c \
../net/ipv4/fib_rules.c \
../net/ipv4/fib_semantics.c \
../net/ipv4/fib_trie.c \
../net/ipv4/icmp.c \
../net/ipv4/igmp.c \
../net/ipv4/inet_connection_sock.c \
../net/ipv4/inet_diag.c \
../net/ipv4/inet_fragment.c \
../net/ipv4/inet_hashtables.c \
../net/ipv4/inet_lro.c \
../net/ipv4/inet_timewait_sock.c \
../net/ipv4/inetpeer.c \
../net/ipv4/ip_forward.c \
../net/ipv4/ip_fragment.c \
../net/ipv4/ip_gre.c \
../net/ipv4/ip_input.c \
../net/ipv4/ip_options.c \
../net/ipv4/ip_output.c \
../net/ipv4/ip_sockglue.c \
../net/ipv4/ipcomp.c \
../net/ipv4/ipconfig.c \
../net/ipv4/ipip.c \
../net/ipv4/ipmr.c \
../net/ipv4/netfilter.c \
../net/ipv4/proc.c \
../net/ipv4/protocol.c \
../net/ipv4/raw.c \
../net/ipv4/route.c \
../net/ipv4/syncookies.c \
../net/ipv4/sysctl_net_ipv4.c \
../net/ipv4/tcp.c \
../net/ipv4/tcp_bic.c \
../net/ipv4/tcp_cong.c \
../net/ipv4/tcp_cubic.c \
../net/ipv4/tcp_diag.c \
../net/ipv4/tcp_highspeed.c \
../net/ipv4/tcp_htcp.c \
../net/ipv4/tcp_hybla.c \
../net/ipv4/tcp_illinois.c \
../net/ipv4/tcp_input.c \
../net/ipv4/tcp_ipv4.c \
../net/ipv4/tcp_lp.c \
../net/ipv4/tcp_minisocks.c \
../net/ipv4/tcp_output.c \
../net/ipv4/tcp_probe.c \
../net/ipv4/tcp_scalable.c \
../net/ipv4/tcp_timer.c \
../net/ipv4/tcp_vegas.c \
../net/ipv4/tcp_veno.c \
../net/ipv4/tcp_westwood.c \
../net/ipv4/tcp_yeah.c \
../net/ipv4/tunnel4.c \
../net/ipv4/udp.c \
../net/ipv4/udplite.c \
../net/ipv4/xfrm4_input.c \
../net/ipv4/xfrm4_mode_beet.c \
../net/ipv4/xfrm4_mode_transport.c \
../net/ipv4/xfrm4_mode_tunnel.c \
../net/ipv4/xfrm4_output.c \
../net/ipv4/xfrm4_policy.c \
../net/ipv4/xfrm4_state.c \
../net/ipv4/xfrm4_tunnel.c 

OBJS += \
./net/ipv4/af_inet.o \
./net/ipv4/ah4.o \
./net/ipv4/arp.o \
./net/ipv4/cipso_ipv4.o \
./net/ipv4/datagram.o \
./net/ipv4/devinet.o \
./net/ipv4/esp4.o \
./net/ipv4/fib_frontend.o \
./net/ipv4/fib_hash.o \
./net/ipv4/fib_rules.o \
./net/ipv4/fib_semantics.o \
./net/ipv4/fib_trie.o \
./net/ipv4/icmp.o \
./net/ipv4/igmp.o \
./net/ipv4/inet_connection_sock.o \
./net/ipv4/inet_diag.o \
./net/ipv4/inet_fragment.o \
./net/ipv4/inet_hashtables.o \
./net/ipv4/inet_lro.o \
./net/ipv4/inet_timewait_sock.o \
./net/ipv4/inetpeer.o \
./net/ipv4/ip_forward.o \
./net/ipv4/ip_fragment.o \
./net/ipv4/ip_gre.o \
./net/ipv4/ip_input.o \
./net/ipv4/ip_options.o \
./net/ipv4/ip_output.o \
./net/ipv4/ip_sockglue.o \
./net/ipv4/ipcomp.o \
./net/ipv4/ipconfig.o \
./net/ipv4/ipip.o \
./net/ipv4/ipmr.o \
./net/ipv4/netfilter.o \
./net/ipv4/proc.o \
./net/ipv4/protocol.o \
./net/ipv4/raw.o \
./net/ipv4/route.o \
./net/ipv4/syncookies.o \
./net/ipv4/sysctl_net_ipv4.o \
./net/ipv4/tcp.o \
./net/ipv4/tcp_bic.o \
./net/ipv4/tcp_cong.o \
./net/ipv4/tcp_cubic.o \
./net/ipv4/tcp_diag.o \
./net/ipv4/tcp_highspeed.o \
./net/ipv4/tcp_htcp.o \
./net/ipv4/tcp_hybla.o \
./net/ipv4/tcp_illinois.o \
./net/ipv4/tcp_input.o \
./net/ipv4/tcp_ipv4.o \
./net/ipv4/tcp_lp.o \
./net/ipv4/tcp_minisocks.o \
./net/ipv4/tcp_output.o \
./net/ipv4/tcp_probe.o \
./net/ipv4/tcp_scalable.o \
./net/ipv4/tcp_timer.o \
./net/ipv4/tcp_vegas.o \
./net/ipv4/tcp_veno.o \
./net/ipv4/tcp_westwood.o \
./net/ipv4/tcp_yeah.o \
./net/ipv4/tunnel4.o \
./net/ipv4/udp.o \
./net/ipv4/udplite.o \
./net/ipv4/xfrm4_input.o \
./net/ipv4/xfrm4_mode_beet.o \
./net/ipv4/xfrm4_mode_transport.o \
./net/ipv4/xfrm4_mode_tunnel.o \
./net/ipv4/xfrm4_output.o \
./net/ipv4/xfrm4_policy.o \
./net/ipv4/xfrm4_state.o \
./net/ipv4/xfrm4_tunnel.o 

C_DEPS += \
./net/ipv4/af_inet.d \
./net/ipv4/ah4.d \
./net/ipv4/arp.d \
./net/ipv4/cipso_ipv4.d \
./net/ipv4/datagram.d \
./net/ipv4/devinet.d \
./net/ipv4/esp4.d \
./net/ipv4/fib_frontend.d \
./net/ipv4/fib_hash.d \
./net/ipv4/fib_rules.d \
./net/ipv4/fib_semantics.d \
./net/ipv4/fib_trie.d \
./net/ipv4/icmp.d \
./net/ipv4/igmp.d \
./net/ipv4/inet_connection_sock.d \
./net/ipv4/inet_diag.d \
./net/ipv4/inet_fragment.d \
./net/ipv4/inet_hashtables.d \
./net/ipv4/inet_lro.d \
./net/ipv4/inet_timewait_sock.d \
./net/ipv4/inetpeer.d \
./net/ipv4/ip_forward.d \
./net/ipv4/ip_fragment.d \
./net/ipv4/ip_gre.d \
./net/ipv4/ip_input.d \
./net/ipv4/ip_options.d \
./net/ipv4/ip_output.d \
./net/ipv4/ip_sockglue.d \
./net/ipv4/ipcomp.d \
./net/ipv4/ipconfig.d \
./net/ipv4/ipip.d \
./net/ipv4/ipmr.d \
./net/ipv4/netfilter.d \
./net/ipv4/proc.d \
./net/ipv4/protocol.d \
./net/ipv4/raw.d \
./net/ipv4/route.d \
./net/ipv4/syncookies.d \
./net/ipv4/sysctl_net_ipv4.d \
./net/ipv4/tcp.d \
./net/ipv4/tcp_bic.d \
./net/ipv4/tcp_cong.d \
./net/ipv4/tcp_cubic.d \
./net/ipv4/tcp_diag.d \
./net/ipv4/tcp_highspeed.d \
./net/ipv4/tcp_htcp.d \
./net/ipv4/tcp_hybla.d \
./net/ipv4/tcp_illinois.d \
./net/ipv4/tcp_input.d \
./net/ipv4/tcp_ipv4.d \
./net/ipv4/tcp_lp.d \
./net/ipv4/tcp_minisocks.d \
./net/ipv4/tcp_output.d \
./net/ipv4/tcp_probe.d \
./net/ipv4/tcp_scalable.d \
./net/ipv4/tcp_timer.d \
./net/ipv4/tcp_vegas.d \
./net/ipv4/tcp_veno.d \
./net/ipv4/tcp_westwood.d \
./net/ipv4/tcp_yeah.d \
./net/ipv4/tunnel4.d \
./net/ipv4/udp.d \
./net/ipv4/udplite.d \
./net/ipv4/xfrm4_input.d \
./net/ipv4/xfrm4_mode_beet.d \
./net/ipv4/xfrm4_mode_transport.d \
./net/ipv4/xfrm4_mode_tunnel.d \
./net/ipv4/xfrm4_output.d \
./net/ipv4/xfrm4_policy.d \
./net/ipv4/xfrm4_state.d \
./net/ipv4/xfrm4_tunnel.d 


# Each subdirectory must supply rules for building sources it contributes
net/ipv4/%.o: ../net/ipv4/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D__KERNEL__=1 -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/include" -I"/home/madhwang/Development/linuxSource/linux-2.6.34.7/arch/x86/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


